// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Acoes.proto

package br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC;

public final class AcoesProtos {
	private AcoesProtos() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface AcoesOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// repeated .MobiPETIC.Acao acao = 1;
		java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao> getAcaoList();

		br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao getAcao(
				int index);

		int getAcaoCount();

		java.util.List<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.AcaoOrBuilder> getAcaoOrBuilderList();

		br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.AcaoOrBuilder getAcaoOrBuilder(
				int index);
	}

	public static final class Acoes extends
			com.google.protobuf.GeneratedMessage implements AcoesOrBuilder {
		// Use Acoes.newBuilder() to construct.
		private Acoes(Builder builder) {
			super(builder);
		}

		private Acoes(boolean noInit) {
		}

		private static final Acoes defaultInstance;

		public static Acoes getDefaultInstance() {
			return defaultInstance;
		}

		public Acoes getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.internal_static_MobiPETIC_Acoes_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.internal_static_MobiPETIC_Acoes_fieldAccessorTable;
		}

		// repeated .MobiPETIC.Acao acao = 1;
		public static final int ACAO_FIELD_NUMBER = 1;
		private java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao> acao_;

		public java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao> getAcaoList() {
			return acao_;
		}

		public java.util.List<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.AcaoOrBuilder> getAcaoOrBuilderList() {
			return acao_;
		}

		public int getAcaoCount() {
			return acao_.size();
		}

		public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao getAcao(
				int index) {
			return acao_.get(index);
		}

		public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.AcaoOrBuilder getAcaoOrBuilder(
				int index) {
			return acao_.get(index);
		}

		private void initFields() {
			acao_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			for (int i = 0; i < getAcaoCount(); i++) {
				if (!getAcao(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < acao_.size(); i++) {
				output.writeMessage(1, acao_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < acao_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(1, acao_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.AcoesOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.internal_static_MobiPETIC_Acoes_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.internal_static_MobiPETIC_Acoes_fieldAccessorTable;
			}

			// Construct using
			// br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getAcaoFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				if (acaoBuilder_ == null) {
					acao_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					acaoBuilder_.clear();
				}
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes
						.getDescriptor();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes getDefaultInstanceForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes
						.getDefaultInstance();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes build() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes buildPartial() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes result = new br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes(
						this);
				int from_bitField0_ = bitField0_;
				if (acaoBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						acao_ = java.util.Collections.unmodifiableList(acao_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.acao_ = acao_;
				} else {
					result.acao_ = acaoBuilder_.build();
				}
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes) {
					return mergeFrom((br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes other) {
				if (other == br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes
						.getDefaultInstance())
					return this;
				if (acaoBuilder_ == null) {
					if (!other.acao_.isEmpty()) {
						if (acao_.isEmpty()) {
							acao_ = other.acao_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureAcaoIsMutable();
							acao_.addAll(other.acao_);
						}
						onChanged();
					}
				} else {
					if (!other.acao_.isEmpty()) {
						if (acaoBuilder_.isEmpty()) {
							acaoBuilder_.dispose();
							acaoBuilder_ = null;
							acao_ = other.acao_;
							bitField0_ = (bitField0_ & ~0x00000001);
							acaoBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getAcaoFieldBuilder()
									: null;
						} else {
							acaoBuilder_.addAllMessages(other.acao_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public final boolean isInitialized() {
				for (int i = 0; i < getAcaoCount(); i++) {
					if (!getAcao(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao.Builder subBuilder = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao
								.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addAcao(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// repeated .MobiPETIC.Acao acao = 1;
			private java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao> acao_ = java.util.Collections
					.emptyList();

			private void ensureAcaoIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					acao_ = new java.util.ArrayList<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao>(
							acao_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.AcaoOrBuilder> acaoBuilder_;

			public java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao> getAcaoList() {
				if (acaoBuilder_ == null) {
					return java.util.Collections.unmodifiableList(acao_);
				} else {
					return acaoBuilder_.getMessageList();
				}
			}

			public int getAcaoCount() {
				if (acaoBuilder_ == null) {
					return acao_.size();
				} else {
					return acaoBuilder_.getCount();
				}
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao getAcao(
					int index) {
				if (acaoBuilder_ == null) {
					return acao_.get(index);
				} else {
					return acaoBuilder_.getMessage(index);
				}
			}

			public Builder setAcao(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao value) {
				if (acaoBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureAcaoIsMutable();
					acao_.set(index, value);
					onChanged();
				} else {
					acaoBuilder_.setMessage(index, value);
				}
				return this;
			}

			public Builder setAcao(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao.Builder builderForValue) {
				if (acaoBuilder_ == null) {
					ensureAcaoIsMutable();
					acao_.set(index, builderForValue.build());
					onChanged();
				} else {
					acaoBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addAcao(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao value) {
				if (acaoBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureAcaoIsMutable();
					acao_.add(value);
					onChanged();
				} else {
					acaoBuilder_.addMessage(value);
				}
				return this;
			}

			public Builder addAcao(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao value) {
				if (acaoBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureAcaoIsMutable();
					acao_.add(index, value);
					onChanged();
				} else {
					acaoBuilder_.addMessage(index, value);
				}
				return this;
			}

			public Builder addAcao(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao.Builder builderForValue) {
				if (acaoBuilder_ == null) {
					ensureAcaoIsMutable();
					acao_.add(builderForValue.build());
					onChanged();
				} else {
					acaoBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			public Builder addAcao(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao.Builder builderForValue) {
				if (acaoBuilder_ == null) {
					ensureAcaoIsMutable();
					acao_.add(index, builderForValue.build());
					onChanged();
				} else {
					acaoBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addAllAcao(
					java.lang.Iterable<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao> values) {
				if (acaoBuilder_ == null) {
					ensureAcaoIsMutable();
					super.addAll(values, acao_);
					onChanged();
				} else {
					acaoBuilder_.addAllMessages(values);
				}
				return this;
			}

			public Builder clearAcao() {
				if (acaoBuilder_ == null) {
					acao_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					acaoBuilder_.clear();
				}
				return this;
			}

			public Builder removeAcao(int index) {
				if (acaoBuilder_ == null) {
					ensureAcaoIsMutable();
					acao_.remove(index);
					onChanged();
				} else {
					acaoBuilder_.remove(index);
				}
				return this;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao.Builder getAcaoBuilder(
					int index) {
				return getAcaoFieldBuilder().getBuilder(index);
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.AcaoOrBuilder getAcaoOrBuilder(
					int index) {
				if (acaoBuilder_ == null) {
					return acao_.get(index);
				} else {
					return acaoBuilder_.getMessageOrBuilder(index);
				}
			}

			public java.util.List<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.AcaoOrBuilder> getAcaoOrBuilderList() {
				if (acaoBuilder_ != null) {
					return acaoBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(acao_);
				}
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao.Builder addAcaoBuilder() {
				return getAcaoFieldBuilder()
						.addBuilder(
								br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao
										.getDefaultInstance());
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao.Builder addAcaoBuilder(
					int index) {
				return getAcaoFieldBuilder()
						.addBuilder(
								index,
								br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao
										.getDefaultInstance());
			}

			public java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao.Builder> getAcaoBuilderList() {
				return getAcaoFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.AcaoOrBuilder> getAcaoFieldBuilder() {
				if (acaoBuilder_ == null) {
					acaoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.AcaoOrBuilder>(
							acao_, ((bitField0_ & 0x00000001) == 0x00000001),
							getParentForChildren(), isClean());
					acao_ = null;
				}
				return acaoBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:MobiPETIC.Acoes)
		}

		static {
			defaultInstance = new Acoes(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:MobiPETIC.Acoes)
	}

	public interface AcaoOrBuilder extends com.google.protobuf.MessageOrBuilder {

		// required string id = 1;
		boolean hasId();

		String getId();

		// required string nome = 2;
		boolean hasNome();

		String getNome();

		// optional string responsavel = 3;
		boolean hasResponsavel();

		String getResponsavel();

		// optional int64 data_inicio = 4;
		boolean hasDataInicio();

		long getDataInicio();

		// optional int64 data_fim = 5;
		boolean hasDataFim();

		long getDataFim();

		// optional int32 custo = 6;
		boolean hasCusto();

		int getCusto();

		// optional int32 esforco = 7;
		boolean hasEsforco();

		int getEsforco();

		// optional string criador = 8;
		boolean hasCriador();

		String getCriador();

		// optional int64 data_criacao = 9;
		boolean hasDataCriacao();

		long getDataCriacao();

		// optional string processo_id = 10;
		boolean hasProcessoId();

		String getProcessoId();

		// optional bool adotada = 11;
		boolean hasAdotada();

		boolean getAdotada();
	}

	public static final class Acao extends com.google.protobuf.GeneratedMessage
			implements AcaoOrBuilder {
		// Use Acao.newBuilder() to construct.
		private Acao(Builder builder) {
			super(builder);
		}

		private Acao(boolean noInit) {
		}

		private static final Acao defaultInstance;

		public static Acao getDefaultInstance() {
			return defaultInstance;
		}

		public Acao getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.internal_static_MobiPETIC_Acao_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.internal_static_MobiPETIC_Acao_fieldAccessorTable;
		}

		private int bitField0_;
		// required string id = 1;
		public static final int ID_FIELD_NUMBER = 1;
		private java.lang.Object id_;

		public boolean hasId() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public String getId() {
			java.lang.Object ref = id_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					id_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getIdBytes() {
			java.lang.Object ref = id_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				id_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required string nome = 2;
		public static final int NOME_FIELD_NUMBER = 2;
		private java.lang.Object nome_;

		public boolean hasNome() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public String getNome() {
			java.lang.Object ref = nome_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					nome_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getNomeBytes() {
			java.lang.Object ref = nome_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				nome_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional string responsavel = 3;
		public static final int RESPONSAVEL_FIELD_NUMBER = 3;
		private java.lang.Object responsavel_;

		public boolean hasResponsavel() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		public String getResponsavel() {
			java.lang.Object ref = responsavel_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					responsavel_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getResponsavelBytes() {
			java.lang.Object ref = responsavel_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				responsavel_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional int64 data_inicio = 4;
		public static final int DATA_INICIO_FIELD_NUMBER = 4;
		private long dataInicio_;

		public boolean hasDataInicio() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		public long getDataInicio() {
			return dataInicio_;
		}

		// optional int64 data_fim = 5;
		public static final int DATA_FIM_FIELD_NUMBER = 5;
		private long dataFim_;

		public boolean hasDataFim() {
			return ((bitField0_ & 0x00000010) == 0x00000010);
		}

		public long getDataFim() {
			return dataFim_;
		}

		// optional int32 custo = 6;
		public static final int CUSTO_FIELD_NUMBER = 6;
		private int custo_;

		public boolean hasCusto() {
			return ((bitField0_ & 0x00000020) == 0x00000020);
		}

		public int getCusto() {
			return custo_;
		}

		// optional int32 esforco = 7;
		public static final int ESFORCO_FIELD_NUMBER = 7;
		private int esforco_;

		public boolean hasEsforco() {
			return ((bitField0_ & 0x00000040) == 0x00000040);
		}

		public int getEsforco() {
			return esforco_;
		}

		// optional string criador = 8;
		public static final int CRIADOR_FIELD_NUMBER = 8;
		private java.lang.Object criador_;

		public boolean hasCriador() {
			return ((bitField0_ & 0x00000080) == 0x00000080);
		}

		public String getCriador() {
			java.lang.Object ref = criador_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					criador_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getCriadorBytes() {
			java.lang.Object ref = criador_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				criador_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional int64 data_criacao = 9;
		public static final int DATA_CRIACAO_FIELD_NUMBER = 9;
		private long dataCriacao_;

		public boolean hasDataCriacao() {
			return ((bitField0_ & 0x00000100) == 0x00000100);
		}

		public long getDataCriacao() {
			return dataCriacao_;
		}

		// optional string processo_id = 10;
		public static final int PROCESSO_ID_FIELD_NUMBER = 10;
		private java.lang.Object processoId_;

		public boolean hasProcessoId() {
			return ((bitField0_ & 0x00000200) == 0x00000200);
		}

		public String getProcessoId() {
			java.lang.Object ref = processoId_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					processoId_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getProcessoIdBytes() {
			java.lang.Object ref = processoId_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				processoId_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional bool adotada = 11;
		public static final int ADOTADA_FIELD_NUMBER = 11;
		private boolean adotada_;

		public boolean hasAdotada() {
			return ((bitField0_ & 0x00000400) == 0x00000400);
		}

		public boolean getAdotada() {
			return adotada_;
		}

		private void initFields() {
			id_ = "";
			nome_ = "";
			responsavel_ = "";
			dataInicio_ = 0L;
			dataFim_ = 0L;
			custo_ = 0;
			esforco_ = 0;
			criador_ = "";
			dataCriacao_ = 0L;
			processoId_ = "";
			adotada_ = false;
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasNome()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getIdBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getNomeBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeBytes(3, getResponsavelBytes());
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeInt64(4, dataInicio_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				output.writeInt64(5, dataFim_);
			}
			if (((bitField0_ & 0x00000020) == 0x00000020)) {
				output.writeInt32(6, custo_);
			}
			if (((bitField0_ & 0x00000040) == 0x00000040)) {
				output.writeInt32(7, esforco_);
			}
			if (((bitField0_ & 0x00000080) == 0x00000080)) {
				output.writeBytes(8, getCriadorBytes());
			}
			if (((bitField0_ & 0x00000100) == 0x00000100)) {
				output.writeInt64(9, dataCriacao_);
			}
			if (((bitField0_ & 0x00000200) == 0x00000200)) {
				output.writeBytes(10, getProcessoIdBytes());
			}
			if (((bitField0_ & 0x00000400) == 0x00000400)) {
				output.writeBool(11, adotada_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						1, getIdBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						2, getNomeBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						3, getResponsavelBytes());
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(
						4, dataInicio_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(
						5, dataFim_);
			}
			if (((bitField0_ & 0x00000020) == 0x00000020)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						6, custo_);
			}
			if (((bitField0_ & 0x00000040) == 0x00000040)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						7, esforco_);
			}
			if (((bitField0_ & 0x00000080) == 0x00000080)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						8, getCriadorBytes());
			}
			if (((bitField0_ & 0x00000100) == 0x00000100)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(
						9, dataCriacao_);
			}
			if (((bitField0_ & 0x00000200) == 0x00000200)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						10, getProcessoIdBytes());
			}
			if (((bitField0_ & 0x00000400) == 0x00000400)) {
				size += com.google.protobuf.CodedOutputStream.computeBoolSize(
						11, adotada_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.AcaoOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.internal_static_MobiPETIC_Acao_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.internal_static_MobiPETIC_Acao_fieldAccessorTable;
			}

			// Construct using
			// br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				id_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				nome_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				responsavel_ = "";
				bitField0_ = (bitField0_ & ~0x00000004);
				dataInicio_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000008);
				dataFim_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000010);
				custo_ = 0;
				bitField0_ = (bitField0_ & ~0x00000020);
				esforco_ = 0;
				bitField0_ = (bitField0_ & ~0x00000040);
				criador_ = "";
				bitField0_ = (bitField0_ & ~0x00000080);
				dataCriacao_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000100);
				processoId_ = "";
				bitField0_ = (bitField0_ & ~0x00000200);
				adotada_ = false;
				bitField0_ = (bitField0_ & ~0x00000400);
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao
						.getDescriptor();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao getDefaultInstanceForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao
						.getDefaultInstance();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao build() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao buildPartial() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao result = new br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.id_ = id_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.nome_ = nome_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.responsavel_ = responsavel_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.dataInicio_ = dataInicio_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000010;
				}
				result.dataFim_ = dataFim_;
				if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
					to_bitField0_ |= 0x00000020;
				}
				result.custo_ = custo_;
				if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
					to_bitField0_ |= 0x00000040;
				}
				result.esforco_ = esforco_;
				if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
					to_bitField0_ |= 0x00000080;
				}
				result.criador_ = criador_;
				if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
					to_bitField0_ |= 0x00000100;
				}
				result.dataCriacao_ = dataCriacao_;
				if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
					to_bitField0_ |= 0x00000200;
				}
				result.processoId_ = processoId_;
				if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
					to_bitField0_ |= 0x00000400;
				}
				result.adotada_ = adotada_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao) {
					return mergeFrom((br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao other) {
				if (other == br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao
						.getDefaultInstance())
					return this;
				if (other.hasId()) {
					setId(other.getId());
				}
				if (other.hasNome()) {
					setNome(other.getNome());
				}
				if (other.hasResponsavel()) {
					setResponsavel(other.getResponsavel());
				}
				if (other.hasDataInicio()) {
					setDataInicio(other.getDataInicio());
				}
				if (other.hasDataFim()) {
					setDataFim(other.getDataFim());
				}
				if (other.hasCusto()) {
					setCusto(other.getCusto());
				}
				if (other.hasEsforco()) {
					setEsforco(other.getEsforco());
				}
				if (other.hasCriador()) {
					setCriador(other.getCriador());
				}
				if (other.hasDataCriacao()) {
					setDataCriacao(other.getDataCriacao());
				}
				if (other.hasProcessoId()) {
					setProcessoId(other.getProcessoId());
				}
				if (other.hasAdotada()) {
					setAdotada(other.getAdotada());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public final boolean isInitialized() {
				if (!hasId()) {

					return false;
				}
				if (!hasNome()) {

					return false;
				}
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						bitField0_ |= 0x00000001;
						id_ = input.readBytes();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						nome_ = input.readBytes();
						break;
					}
					case 26: {
						bitField0_ |= 0x00000004;
						responsavel_ = input.readBytes();
						break;
					}
					case 32: {
						bitField0_ |= 0x00000008;
						dataInicio_ = input.readInt64();
						break;
					}
					case 40: {
						bitField0_ |= 0x00000010;
						dataFim_ = input.readInt64();
						break;
					}
					case 48: {
						bitField0_ |= 0x00000020;
						custo_ = input.readInt32();
						break;
					}
					case 56: {
						bitField0_ |= 0x00000040;
						esforco_ = input.readInt32();
						break;
					}
					case 66: {
						bitField0_ |= 0x00000080;
						criador_ = input.readBytes();
						break;
					}
					case 72: {
						bitField0_ |= 0x00000100;
						dataCriacao_ = input.readInt64();
						break;
					}
					case 82: {
						bitField0_ |= 0x00000200;
						processoId_ = input.readBytes();
						break;
					}
					case 88: {
						bitField0_ |= 0x00000400;
						adotada_ = input.readBool();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required string id = 1;
			private java.lang.Object id_ = "";

			public boolean hasId() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public String getId() {
				java.lang.Object ref = id_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					id_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setId(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				id_ = value;
				onChanged();
				return this;
			}

			public Builder clearId() {
				bitField0_ = (bitField0_ & ~0x00000001);
				id_ = getDefaultInstance().getId();
				onChanged();
				return this;
			}

			void setId(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000001;
				id_ = value;
				onChanged();
			}

			// required string nome = 2;
			private java.lang.Object nome_ = "";

			public boolean hasNome() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public String getNome() {
				java.lang.Object ref = nome_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					nome_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setNome(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				nome_ = value;
				onChanged();
				return this;
			}

			public Builder clearNome() {
				bitField0_ = (bitField0_ & ~0x00000002);
				nome_ = getDefaultInstance().getNome();
				onChanged();
				return this;
			}

			void setNome(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000002;
				nome_ = value;
				onChanged();
			}

			// optional string responsavel = 3;
			private java.lang.Object responsavel_ = "";

			public boolean hasResponsavel() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			public String getResponsavel() {
				java.lang.Object ref = responsavel_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					responsavel_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setResponsavel(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				responsavel_ = value;
				onChanged();
				return this;
			}

			public Builder clearResponsavel() {
				bitField0_ = (bitField0_ & ~0x00000004);
				responsavel_ = getDefaultInstance().getResponsavel();
				onChanged();
				return this;
			}

			void setResponsavel(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000004;
				responsavel_ = value;
				onChanged();
			}

			// optional int64 data_inicio = 4;
			private long dataInicio_;

			public boolean hasDataInicio() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			public long getDataInicio() {
				return dataInicio_;
			}

			public Builder setDataInicio(long value) {
				bitField0_ |= 0x00000008;
				dataInicio_ = value;
				onChanged();
				return this;
			}

			public Builder clearDataInicio() {
				bitField0_ = (bitField0_ & ~0x00000008);
				dataInicio_ = 0L;
				onChanged();
				return this;
			}

			// optional int64 data_fim = 5;
			private long dataFim_;

			public boolean hasDataFim() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}

			public long getDataFim() {
				return dataFim_;
			}

			public Builder setDataFim(long value) {
				bitField0_ |= 0x00000010;
				dataFim_ = value;
				onChanged();
				return this;
			}

			public Builder clearDataFim() {
				bitField0_ = (bitField0_ & ~0x00000010);
				dataFim_ = 0L;
				onChanged();
				return this;
			}

			// optional int32 custo = 6;
			private int custo_;

			public boolean hasCusto() {
				return ((bitField0_ & 0x00000020) == 0x00000020);
			}

			public int getCusto() {
				return custo_;
			}

			public Builder setCusto(int value) {
				bitField0_ |= 0x00000020;
				custo_ = value;
				onChanged();
				return this;
			}

			public Builder clearCusto() {
				bitField0_ = (bitField0_ & ~0x00000020);
				custo_ = 0;
				onChanged();
				return this;
			}

			// optional int32 esforco = 7;
			private int esforco_;

			public boolean hasEsforco() {
				return ((bitField0_ & 0x00000040) == 0x00000040);
			}

			public int getEsforco() {
				return esforco_;
			}

			public Builder setEsforco(int value) {
				bitField0_ |= 0x00000040;
				esforco_ = value;
				onChanged();
				return this;
			}

			public Builder clearEsforco() {
				bitField0_ = (bitField0_ & ~0x00000040);
				esforco_ = 0;
				onChanged();
				return this;
			}

			// optional string criador = 8;
			private java.lang.Object criador_ = "";

			public boolean hasCriador() {
				return ((bitField0_ & 0x00000080) == 0x00000080);
			}

			public String getCriador() {
				java.lang.Object ref = criador_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					criador_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setCriador(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000080;
				criador_ = value;
				onChanged();
				return this;
			}

			public Builder clearCriador() {
				bitField0_ = (bitField0_ & ~0x00000080);
				criador_ = getDefaultInstance().getCriador();
				onChanged();
				return this;
			}

			void setCriador(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000080;
				criador_ = value;
				onChanged();
			}

			// optional int64 data_criacao = 9;
			private long dataCriacao_;

			public boolean hasDataCriacao() {
				return ((bitField0_ & 0x00000100) == 0x00000100);
			}

			public long getDataCriacao() {
				return dataCriacao_;
			}

			public Builder setDataCriacao(long value) {
				bitField0_ |= 0x00000100;
				dataCriacao_ = value;
				onChanged();
				return this;
			}

			public Builder clearDataCriacao() {
				bitField0_ = (bitField0_ & ~0x00000100);
				dataCriacao_ = 0L;
				onChanged();
				return this;
			}

			// optional string processo_id = 10;
			private java.lang.Object processoId_ = "";

			public boolean hasProcessoId() {
				return ((bitField0_ & 0x00000200) == 0x00000200);
			}

			public String getProcessoId() {
				java.lang.Object ref = processoId_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					processoId_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setProcessoId(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000200;
				processoId_ = value;
				onChanged();
				return this;
			}

			public Builder clearProcessoId() {
				bitField0_ = (bitField0_ & ~0x00000200);
				processoId_ = getDefaultInstance().getProcessoId();
				onChanged();
				return this;
			}

			void setProcessoId(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000200;
				processoId_ = value;
				onChanged();
			}

			// optional bool adotada = 11;
			private boolean adotada_;

			public boolean hasAdotada() {
				return ((bitField0_ & 0x00000400) == 0x00000400);
			}

			public boolean getAdotada() {
				return adotada_;
			}

			public Builder setAdotada(boolean value) {
				bitField0_ |= 0x00000400;
				adotada_ = value;
				onChanged();
				return this;
			}

			public Builder clearAdotada() {
				bitField0_ = (bitField0_ & ~0x00000400);
				adotada_ = false;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:MobiPETIC.Acao)
		}

		static {
			defaultInstance = new Acao(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:MobiPETIC.Acao)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_MobiPETIC_Acoes_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_MobiPETIC_Acoes_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_MobiPETIC_Acao_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_MobiPETIC_Acao_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\013Acoes.proto\022\tMobiPETIC\"&\n\005Acoes\022\035\n\004aca"
				+ "o\030\001 \003(\0132\017.MobiPETIC.Acao\"\311\001\n\004Acao\022\n\n\002id\030"
				+ "\001 \002(\t\022\014\n\004nome\030\002 \002(\t\022\023\n\013responsavel\030\003 \001(\t"
				+ "\022\023\n\013data_inicio\030\004 \001(\003\022\020\n\010data_fim\030\005 \001(\003\022"
				+ "\r\n\005custo\030\006 \001(\005\022\017\n\007esforco\030\007 \001(\005\022\017\n\007criad"
				+ "or\030\010 \001(\t\022\024\n\014data_criacao\030\t \001(\003\022\023\n\013proces"
				+ "so_id\030\n \001(\t\022\017\n\007adotada\030\013 \001(\010BC\n4br.ufs.d"
				+ "comp.gpes.peticwizard.presentation.MobiP"
				+ "ETICB\013AcoesProtos" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_MobiPETIC_Acoes_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_MobiPETIC_Acoes_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_MobiPETIC_Acoes_descriptor,
						new java.lang.String[] { "Acao", },
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes.class,
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acoes.Builder.class);
				internal_static_MobiPETIC_Acao_descriptor = getDescriptor()
						.getMessageTypes().get(1);
				internal_static_MobiPETIC_Acao_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_MobiPETIC_Acao_descriptor,
						new java.lang.String[] { "Id", "Nome", "Responsavel",
								"DataInicio", "DataFim", "Custo", "Esforco",
								"Criador", "DataCriacao", "ProcessoId",
								"Adotada", },
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao.class,
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AcoesProtos.Acao.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
