// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProcessoQuestoesfile.proto

package br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC;

public final class ProcessoQuestoesMaturidadeProtos {
	private ProcessoQuestoesMaturidadeProtos() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface ProcessoQuestoesOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// repeated .MobiPETIC.ProcessoQuestao processo_questao = 1;
		java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao> getProcessoQuestaoList();

		br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao getProcessoQuestao(
				int index);

		int getProcessoQuestaoCount();

		java.util.List<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestaoOrBuilder> getProcessoQuestaoOrBuilderList();

		br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestaoOrBuilder getProcessoQuestaoOrBuilder(
				int index);
	}

	public static final class ProcessoQuestoes extends
			com.google.protobuf.GeneratedMessage implements
			ProcessoQuestoesOrBuilder {
		// Use ProcessoQuestoes.newBuilder() to construct.
		private ProcessoQuestoes(Builder builder) {
			super(builder);
		}

		private ProcessoQuestoes(boolean noInit) {
		}

		private static final ProcessoQuestoes defaultInstance;

		public static ProcessoQuestoes getDefaultInstance() {
			return defaultInstance;
		}

		public ProcessoQuestoes getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.internal_static_MobiPETIC_ProcessoQuestoes_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.internal_static_MobiPETIC_ProcessoQuestoes_fieldAccessorTable;
		}

		// repeated .MobiPETIC.ProcessoQuestao processo_questao = 1;
		public static final int PROCESSO_QUESTAO_FIELD_NUMBER = 1;
		private java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao> processoQuestao_;

		public java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao> getProcessoQuestaoList() {
			return processoQuestao_;
		}

		public java.util.List<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestaoOrBuilder> getProcessoQuestaoOrBuilderList() {
			return processoQuestao_;
		}

		public int getProcessoQuestaoCount() {
			return processoQuestao_.size();
		}

		public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao getProcessoQuestao(
				int index) {
			return processoQuestao_.get(index);
		}

		public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestaoOrBuilder getProcessoQuestaoOrBuilder(
				int index) {
			return processoQuestao_.get(index);
		}

		private void initFields() {
			processoQuestao_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			for (int i = 0; i < getProcessoQuestaoCount(); i++) {
				if (!getProcessoQuestao(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < processoQuestao_.size(); i++) {
				output.writeMessage(1, processoQuestao_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < processoQuestao_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(1, processoQuestao_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoesOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.internal_static_MobiPETIC_ProcessoQuestoes_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.internal_static_MobiPETIC_ProcessoQuestoes_fieldAccessorTable;
			}

			// Construct using
			// br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getProcessoQuestaoFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				if (processoQuestaoBuilder_ == null) {
					processoQuestao_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					processoQuestaoBuilder_.clear();
				}
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes
						.getDescriptor();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes getDefaultInstanceForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes
						.getDefaultInstance();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes build() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes buildPartial() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes result = new br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes(
						this);
				int from_bitField0_ = bitField0_;
				if (processoQuestaoBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						processoQuestao_ = java.util.Collections
								.unmodifiableList(processoQuestao_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.processoQuestao_ = processoQuestao_;
				} else {
					result.processoQuestao_ = processoQuestaoBuilder_.build();
				}
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes) {
					return mergeFrom((br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes other) {
				if (other == br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes
						.getDefaultInstance())
					return this;
				if (processoQuestaoBuilder_ == null) {
					if (!other.processoQuestao_.isEmpty()) {
						if (processoQuestao_.isEmpty()) {
							processoQuestao_ = other.processoQuestao_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureProcessoQuestaoIsMutable();
							processoQuestao_.addAll(other.processoQuestao_);
						}
						onChanged();
					}
				} else {
					if (!other.processoQuestao_.isEmpty()) {
						if (processoQuestaoBuilder_.isEmpty()) {
							processoQuestaoBuilder_.dispose();
							processoQuestaoBuilder_ = null;
							processoQuestao_ = other.processoQuestao_;
							bitField0_ = (bitField0_ & ~0x00000001);
							processoQuestaoBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getProcessoQuestaoFieldBuilder()
									: null;
						} else {
							processoQuestaoBuilder_
									.addAllMessages(other.processoQuestao_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public final boolean isInitialized() {
				for (int i = 0; i < getProcessoQuestaoCount(); i++) {
					if (!getProcessoQuestao(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao.Builder subBuilder = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao
								.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addProcessoQuestao(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// repeated .MobiPETIC.ProcessoQuestao processo_questao = 1;
			private java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao> processoQuestao_ = java.util.Collections
					.emptyList();

			private void ensureProcessoQuestaoIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					processoQuestao_ = new java.util.ArrayList<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao>(
							processoQuestao_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestaoOrBuilder> processoQuestaoBuilder_;

			public java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao> getProcessoQuestaoList() {
				if (processoQuestaoBuilder_ == null) {
					return java.util.Collections
							.unmodifiableList(processoQuestao_);
				} else {
					return processoQuestaoBuilder_.getMessageList();
				}
			}

			public int getProcessoQuestaoCount() {
				if (processoQuestaoBuilder_ == null) {
					return processoQuestao_.size();
				} else {
					return processoQuestaoBuilder_.getCount();
				}
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao getProcessoQuestao(
					int index) {
				if (processoQuestaoBuilder_ == null) {
					return processoQuestao_.get(index);
				} else {
					return processoQuestaoBuilder_.getMessage(index);
				}
			}

			public Builder setProcessoQuestao(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao value) {
				if (processoQuestaoBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureProcessoQuestaoIsMutable();
					processoQuestao_.set(index, value);
					onChanged();
				} else {
					processoQuestaoBuilder_.setMessage(index, value);
				}
				return this;
			}

			public Builder setProcessoQuestao(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao.Builder builderForValue) {
				if (processoQuestaoBuilder_ == null) {
					ensureProcessoQuestaoIsMutable();
					processoQuestao_.set(index, builderForValue.build());
					onChanged();
				} else {
					processoQuestaoBuilder_.setMessage(index,
							builderForValue.build());
				}
				return this;
			}

			public Builder addProcessoQuestao(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao value) {
				if (processoQuestaoBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureProcessoQuestaoIsMutable();
					processoQuestao_.add(value);
					onChanged();
				} else {
					processoQuestaoBuilder_.addMessage(value);
				}
				return this;
			}

			public Builder addProcessoQuestao(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao value) {
				if (processoQuestaoBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureProcessoQuestaoIsMutable();
					processoQuestao_.add(index, value);
					onChanged();
				} else {
					processoQuestaoBuilder_.addMessage(index, value);
				}
				return this;
			}

			public Builder addProcessoQuestao(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao.Builder builderForValue) {
				if (processoQuestaoBuilder_ == null) {
					ensureProcessoQuestaoIsMutable();
					processoQuestao_.add(builderForValue.build());
					onChanged();
				} else {
					processoQuestaoBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			public Builder addProcessoQuestao(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao.Builder builderForValue) {
				if (processoQuestaoBuilder_ == null) {
					ensureProcessoQuestaoIsMutable();
					processoQuestao_.add(index, builderForValue.build());
					onChanged();
				} else {
					processoQuestaoBuilder_.addMessage(index,
							builderForValue.build());
				}
				return this;
			}

			public Builder addAllProcessoQuestao(
					java.lang.Iterable<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao> values) {
				if (processoQuestaoBuilder_ == null) {
					ensureProcessoQuestaoIsMutable();
					super.addAll(values, processoQuestao_);
					onChanged();
				} else {
					processoQuestaoBuilder_.addAllMessages(values);
				}
				return this;
			}

			public Builder clearProcessoQuestao() {
				if (processoQuestaoBuilder_ == null) {
					processoQuestao_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					processoQuestaoBuilder_.clear();
				}
				return this;
			}

			public Builder removeProcessoQuestao(int index) {
				if (processoQuestaoBuilder_ == null) {
					ensureProcessoQuestaoIsMutable();
					processoQuestao_.remove(index);
					onChanged();
				} else {
					processoQuestaoBuilder_.remove(index);
				}
				return this;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao.Builder getProcessoQuestaoBuilder(
					int index) {
				return getProcessoQuestaoFieldBuilder().getBuilder(index);
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestaoOrBuilder getProcessoQuestaoOrBuilder(
					int index) {
				if (processoQuestaoBuilder_ == null) {
					return processoQuestao_.get(index);
				} else {
					return processoQuestaoBuilder_.getMessageOrBuilder(index);
				}
			}

			public java.util.List<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestaoOrBuilder> getProcessoQuestaoOrBuilderList() {
				if (processoQuestaoBuilder_ != null) {
					return processoQuestaoBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections
							.unmodifiableList(processoQuestao_);
				}
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao.Builder addProcessoQuestaoBuilder() {
				return getProcessoQuestaoFieldBuilder()
						.addBuilder(
								br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao
										.getDefaultInstance());
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao.Builder addProcessoQuestaoBuilder(
					int index) {
				return getProcessoQuestaoFieldBuilder()
						.addBuilder(
								index,
								br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao
										.getDefaultInstance());
			}

			public java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao.Builder> getProcessoQuestaoBuilderList() {
				return getProcessoQuestaoFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestaoOrBuilder> getProcessoQuestaoFieldBuilder() {
				if (processoQuestaoBuilder_ == null) {
					processoQuestaoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestaoOrBuilder>(
							processoQuestao_,
							((bitField0_ & 0x00000001) == 0x00000001),
							getParentForChildren(), isClean());
					processoQuestao_ = null;
				}
				return processoQuestaoBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:MobiPETIC.ProcessoQuestoes)
		}

		static {
			defaultInstance = new ProcessoQuestoes(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:MobiPETIC.ProcessoQuestoes)
	}

	public interface ProcessoQuestaoOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// required int32 id_questao = 1;
		boolean hasIdQuestao();

		int getIdQuestao();

		// required string id_processo = 2;
		boolean hasIdProcesso();

		String getIdProcesso();

		// required string marcado = 3;
		boolean hasMarcado();

		String getMarcado();
	}

	public static final class ProcessoQuestao extends
			com.google.protobuf.GeneratedMessage implements
			ProcessoQuestaoOrBuilder {
		// Use ProcessoQuestao.newBuilder() to construct.
		private ProcessoQuestao(Builder builder) {
			super(builder);
		}

		private ProcessoQuestao(boolean noInit) {
		}

		private static final ProcessoQuestao defaultInstance;

		public static ProcessoQuestao getDefaultInstance() {
			return defaultInstance;
		}

		public ProcessoQuestao getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.internal_static_MobiPETIC_ProcessoQuestao_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.internal_static_MobiPETIC_ProcessoQuestao_fieldAccessorTable;
		}

		private int bitField0_;
		// required int32 id_questao = 1;
		public static final int ID_QUESTAO_FIELD_NUMBER = 1;
		private int idQuestao_;

		public boolean hasIdQuestao() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public int getIdQuestao() {
			return idQuestao_;
		}

		// required string id_processo = 2;
		public static final int ID_PROCESSO_FIELD_NUMBER = 2;
		private java.lang.Object idProcesso_;

		public boolean hasIdProcesso() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public String getIdProcesso() {
			java.lang.Object ref = idProcesso_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					idProcesso_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getIdProcessoBytes() {
			java.lang.Object ref = idProcesso_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				idProcesso_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required string marcado = 3;
		public static final int MARCADO_FIELD_NUMBER = 3;
		private java.lang.Object marcado_;

		public boolean hasMarcado() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		public String getMarcado() {
			java.lang.Object ref = marcado_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					marcado_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getMarcadoBytes() {
			java.lang.Object ref = marcado_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				marcado_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			idQuestao_ = 0;
			idProcesso_ = "";
			marcado_ = "";
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasIdQuestao()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasIdProcesso()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasMarcado()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(1, idQuestao_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getIdProcessoBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeBytes(3, getMarcadoBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						1, idQuestao_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						2, getIdProcessoBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						3, getMarcadoBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestaoOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.internal_static_MobiPETIC_ProcessoQuestao_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.internal_static_MobiPETIC_ProcessoQuestao_fieldAccessorTable;
			}

			// Construct using
			// br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				idQuestao_ = 0;
				bitField0_ = (bitField0_ & ~0x00000001);
				idProcesso_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				marcado_ = "";
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao
						.getDescriptor();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao getDefaultInstanceForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao
						.getDefaultInstance();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao build() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao buildPartial() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao result = new br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.idQuestao_ = idQuestao_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.idProcesso_ = idProcesso_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.marcado_ = marcado_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao) {
					return mergeFrom((br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao other) {
				if (other == br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao
						.getDefaultInstance())
					return this;
				if (other.hasIdQuestao()) {
					setIdQuestao(other.getIdQuestao());
				}
				if (other.hasIdProcesso()) {
					setIdProcesso(other.getIdProcesso());
				}
				if (other.hasMarcado()) {
					setMarcado(other.getMarcado());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public final boolean isInitialized() {
				if (!hasIdQuestao()) {

					return false;
				}
				if (!hasIdProcesso()) {

					return false;
				}
				if (!hasMarcado()) {

					return false;
				}
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						idQuestao_ = input.readInt32();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						idProcesso_ = input.readBytes();
						break;
					}
					case 26: {
						bitField0_ |= 0x00000004;
						marcado_ = input.readBytes();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required int32 id_questao = 1;
			private int idQuestao_;

			public boolean hasIdQuestao() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public int getIdQuestao() {
				return idQuestao_;
			}

			public Builder setIdQuestao(int value) {
				bitField0_ |= 0x00000001;
				idQuestao_ = value;
				onChanged();
				return this;
			}

			public Builder clearIdQuestao() {
				bitField0_ = (bitField0_ & ~0x00000001);
				idQuestao_ = 0;
				onChanged();
				return this;
			}

			// required string id_processo = 2;
			private java.lang.Object idProcesso_ = "";

			public boolean hasIdProcesso() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public String getIdProcesso() {
				java.lang.Object ref = idProcesso_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					idProcesso_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setIdProcesso(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				idProcesso_ = value;
				onChanged();
				return this;
			}

			public Builder clearIdProcesso() {
				bitField0_ = (bitField0_ & ~0x00000002);
				idProcesso_ = getDefaultInstance().getIdProcesso();
				onChanged();
				return this;
			}

			void setIdProcesso(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000002;
				idProcesso_ = value;
				onChanged();
			}

			// required string marcado = 3;
			private java.lang.Object marcado_ = "";

			public boolean hasMarcado() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			public String getMarcado() {
				java.lang.Object ref = marcado_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					marcado_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setMarcado(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				marcado_ = value;
				onChanged();
				return this;
			}

			public Builder clearMarcado() {
				bitField0_ = (bitField0_ & ~0x00000004);
				marcado_ = getDefaultInstance().getMarcado();
				onChanged();
				return this;
			}

			void setMarcado(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000004;
				marcado_ = value;
				onChanged();
			}

			// @@protoc_insertion_point(builder_scope:MobiPETIC.ProcessoQuestao)
		}

		static {
			defaultInstance = new ProcessoQuestao(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:MobiPETIC.ProcessoQuestao)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_MobiPETIC_ProcessoQuestoes_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_MobiPETIC_ProcessoQuestoes_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_MobiPETIC_ProcessoQuestao_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_MobiPETIC_ProcessoQuestao_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\032ProcessoQuestoesfile.proto\022\tMobiPETIC\""
				+ "H\n\020ProcessoQuestoes\0224\n\020processo_questao\030"
				+ "\001 \003(\0132\032.MobiPETIC.ProcessoQuestao\"K\n\017Pro"
				+ "cessoQuestao\022\022\n\nid_questao\030\001 \002(\005\022\023\n\013id_p"
				+ "rocesso\030\002 \002(\t\022\017\n\007marcado\030\003 \002(\tBX\n4br.ufs"
				+ ".dcomp.gpes.peticwizard.presentation.Mob"
				+ "iPETICB ProcessoQuestoesMaturidadeProtos" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_MobiPETIC_ProcessoQuestoes_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_MobiPETIC_ProcessoQuestoes_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_MobiPETIC_ProcessoQuestoes_descriptor,
						new java.lang.String[] { "ProcessoQuestao", },
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes.class,
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestoes.Builder.class);
				internal_static_MobiPETIC_ProcessoQuestao_descriptor = getDescriptor()
						.getMessageTypes().get(1);
				internal_static_MobiPETIC_ProcessoQuestao_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_MobiPETIC_ProcessoQuestao_descriptor,
						new java.lang.String[] { "IdQuestao", "IdProcesso",
								"Marcado", },
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao.class,
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessoQuestoesMaturidadeProtos.ProcessoQuestao.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
