// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Processosfile.proto

package br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC;

public final class ProcessosProtos {
	private ProcessosProtos() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public enum Maturidade implements com.google.protobuf.ProtocolMessageEnum {
		INDEFINIDA(0, 0), INEXISTENTE(1, 1), MINIMO(2, 2), SEGURO(3, 3), SATISFATORIO(
				4, 4), ESTADOIDEAL(5, 5), ;

		public static final int INDEFINIDA_VALUE = 0;
		public static final int INEXISTENTE_VALUE = 1;
		public static final int MINIMO_VALUE = 2;
		public static final int SEGURO_VALUE = 3;
		public static final int SATISFATORIO_VALUE = 4;
		public static final int ESTADOIDEAL_VALUE = 5;

		public final int getNumber() {
			return value;
		}

		public static Maturidade valueOf(int value) {
			switch (value) {
			case 0:
				return INDEFINIDA;
			case 1:
				return INEXISTENTE;
			case 2:
				return MINIMO;
			case 3:
				return SEGURO;
			case 4:
				return SATISFATORIO;
			case 5:
				return ESTADOIDEAL;
			default:
				return null;
			}
		}

		public static com.google.protobuf.Internal.EnumLiteMap<Maturidade> internalGetValueMap() {
			return internalValueMap;
		}

		private static com.google.protobuf.Internal.EnumLiteMap<Maturidade> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<Maturidade>() {
			public Maturidade findValueByNumber(int number) {
				return Maturidade.valueOf(number);
			}
		};

		public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
			return getDescriptor().getValues().get(index);
		}

		public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
			return getDescriptor();
		}

		public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos
					.getDescriptor().getEnumTypes().get(0);
		}

		private static final Maturidade[] VALUES = { INDEFINIDA, INEXISTENTE,
				MINIMO, SEGURO, SATISFATORIO, ESTADOIDEAL, };

		public static Maturidade valueOf(
				com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
			if (desc.getType() != getDescriptor()) {
				throw new java.lang.IllegalArgumentException(
						"EnumValueDescriptor is not for this type.");
			}
			return VALUES[desc.getIndex()];
		}

		private final int index;
		private final int value;

		private Maturidade(int index, int value) {
			this.index = index;
			this.value = value;
		}

		// @@protoc_insertion_point(enum_scope:MobiPETIC.Maturidade)
	}

	public interface ProcessosOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// repeated .MobiPETIC.Processo processo = 1;
		java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo> getProcessoList();

		br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo getProcesso(
				int index);

		int getProcessoCount();

		java.util.List<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.ProcessoOrBuilder> getProcessoOrBuilderList();

		br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.ProcessoOrBuilder getProcessoOrBuilder(
				int index);
	}

	public static final class Processos extends
			com.google.protobuf.GeneratedMessage implements ProcessosOrBuilder {
		// Use Processos.newBuilder() to construct.
		private Processos(Builder builder) {
			super(builder);
		}

		private Processos(boolean noInit) {
		}

		private static final Processos defaultInstance;

		public static Processos getDefaultInstance() {
			return defaultInstance;
		}

		public Processos getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.internal_static_MobiPETIC_Processos_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.internal_static_MobiPETIC_Processos_fieldAccessorTable;
		}

		// repeated .MobiPETIC.Processo processo = 1;
		public static final int PROCESSO_FIELD_NUMBER = 1;
		private java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo> processo_;

		public java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo> getProcessoList() {
			return processo_;
		}

		public java.util.List<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.ProcessoOrBuilder> getProcessoOrBuilderList() {
			return processo_;
		}

		public int getProcessoCount() {
			return processo_.size();
		}

		public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo getProcesso(
				int index) {
			return processo_.get(index);
		}

		public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.ProcessoOrBuilder getProcessoOrBuilder(
				int index) {
			return processo_.get(index);
		}

		private void initFields() {
			processo_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			for (int i = 0; i < getProcessoCount(); i++) {
				if (!getProcesso(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < processo_.size(); i++) {
				output.writeMessage(1, processo_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < processo_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(1, processo_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.ProcessosOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.internal_static_MobiPETIC_Processos_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.internal_static_MobiPETIC_Processos_fieldAccessorTable;
			}

			// Construct using
			// br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getProcessoFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				if (processoBuilder_ == null) {
					processo_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					processoBuilder_.clear();
				}
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos
						.getDescriptor();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos getDefaultInstanceForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos
						.getDefaultInstance();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos build() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos buildPartial() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos result = new br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos(
						this);
				int from_bitField0_ = bitField0_;
				if (processoBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						processo_ = java.util.Collections
								.unmodifiableList(processo_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.processo_ = processo_;
				} else {
					result.processo_ = processoBuilder_.build();
				}
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos) {
					return mergeFrom((br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos other) {
				if (other == br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos
						.getDefaultInstance())
					return this;
				if (processoBuilder_ == null) {
					if (!other.processo_.isEmpty()) {
						if (processo_.isEmpty()) {
							processo_ = other.processo_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureProcessoIsMutable();
							processo_.addAll(other.processo_);
						}
						onChanged();
					}
				} else {
					if (!other.processo_.isEmpty()) {
						if (processoBuilder_.isEmpty()) {
							processoBuilder_.dispose();
							processoBuilder_ = null;
							processo_ = other.processo_;
							bitField0_ = (bitField0_ & ~0x00000001);
							processoBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getProcessoFieldBuilder()
									: null;
						} else {
							processoBuilder_.addAllMessages(other.processo_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public final boolean isInitialized() {
				for (int i = 0; i < getProcessoCount(); i++) {
					if (!getProcesso(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo.Builder subBuilder = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo
								.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addProcesso(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// repeated .MobiPETIC.Processo processo = 1;
			private java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo> processo_ = java.util.Collections
					.emptyList();

			private void ensureProcessoIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					processo_ = new java.util.ArrayList<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo>(
							processo_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.ProcessoOrBuilder> processoBuilder_;

			public java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo> getProcessoList() {
				if (processoBuilder_ == null) {
					return java.util.Collections.unmodifiableList(processo_);
				} else {
					return processoBuilder_.getMessageList();
				}
			}

			public int getProcessoCount() {
				if (processoBuilder_ == null) {
					return processo_.size();
				} else {
					return processoBuilder_.getCount();
				}
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo getProcesso(
					int index) {
				if (processoBuilder_ == null) {
					return processo_.get(index);
				} else {
					return processoBuilder_.getMessage(index);
				}
			}

			public Builder setProcesso(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo value) {
				if (processoBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureProcessoIsMutable();
					processo_.set(index, value);
					onChanged();
				} else {
					processoBuilder_.setMessage(index, value);
				}
				return this;
			}

			public Builder setProcesso(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo.Builder builderForValue) {
				if (processoBuilder_ == null) {
					ensureProcessoIsMutable();
					processo_.set(index, builderForValue.build());
					onChanged();
				} else {
					processoBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addProcesso(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo value) {
				if (processoBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureProcessoIsMutable();
					processo_.add(value);
					onChanged();
				} else {
					processoBuilder_.addMessage(value);
				}
				return this;
			}

			public Builder addProcesso(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo value) {
				if (processoBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureProcessoIsMutable();
					processo_.add(index, value);
					onChanged();
				} else {
					processoBuilder_.addMessage(index, value);
				}
				return this;
			}

			public Builder addProcesso(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo.Builder builderForValue) {
				if (processoBuilder_ == null) {
					ensureProcessoIsMutable();
					processo_.add(builderForValue.build());
					onChanged();
				} else {
					processoBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			public Builder addProcesso(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo.Builder builderForValue) {
				if (processoBuilder_ == null) {
					ensureProcessoIsMutable();
					processo_.add(index, builderForValue.build());
					onChanged();
				} else {
					processoBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addAllProcesso(
					java.lang.Iterable<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo> values) {
				if (processoBuilder_ == null) {
					ensureProcessoIsMutable();
					super.addAll(values, processo_);
					onChanged();
				} else {
					processoBuilder_.addAllMessages(values);
				}
				return this;
			}

			public Builder clearProcesso() {
				if (processoBuilder_ == null) {
					processo_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					processoBuilder_.clear();
				}
				return this;
			}

			public Builder removeProcesso(int index) {
				if (processoBuilder_ == null) {
					ensureProcessoIsMutable();
					processo_.remove(index);
					onChanged();
				} else {
					processoBuilder_.remove(index);
				}
				return this;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo.Builder getProcessoBuilder(
					int index) {
				return getProcessoFieldBuilder().getBuilder(index);
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.ProcessoOrBuilder getProcessoOrBuilder(
					int index) {
				if (processoBuilder_ == null) {
					return processo_.get(index);
				} else {
					return processoBuilder_.getMessageOrBuilder(index);
				}
			}

			public java.util.List<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.ProcessoOrBuilder> getProcessoOrBuilderList() {
				if (processoBuilder_ != null) {
					return processoBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(processo_);
				}
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo.Builder addProcessoBuilder() {
				return getProcessoFieldBuilder()
						.addBuilder(
								br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo
										.getDefaultInstance());
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo.Builder addProcessoBuilder(
					int index) {
				return getProcessoFieldBuilder()
						.addBuilder(
								index,
								br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo
										.getDefaultInstance());
			}

			public java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo.Builder> getProcessoBuilderList() {
				return getProcessoFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.ProcessoOrBuilder> getProcessoFieldBuilder() {
				if (processoBuilder_ == null) {
					processoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.ProcessoOrBuilder>(
							processo_,
							((bitField0_ & 0x00000001) == 0x00000001),
							getParentForChildren(), isClean());
					processo_ = null;
				}
				return processoBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:MobiPETIC.Processos)
		}

		static {
			defaultInstance = new Processos(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:MobiPETIC.Processos)
	}

	public interface ProcessoOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// required string id = 1;
		boolean hasId();

		String getId();

		// required string nome = 2;
		boolean hasNome();

		String getNome();

		// optional bool e_prioritario = 3;
		boolean hasEPrioritario();

		boolean getEPrioritario();

		// optional bool prioridade_def = 4;
		boolean hasPrioridadeDef();

		boolean getPrioridadeDef();

		// optional string descricao = 5;
		boolean hasDescricao();

		String getDescricao();

		// optional string entradas = 6;
		boolean hasEntradas();

		String getEntradas();

		// optional string saidas = 7;
		boolean hasSaidas();

		String getSaidas();

		// optional string responsavel = 8;
		boolean hasResponsavel();

		String getResponsavel();

		// optional string stakeholders = 9;
		boolean hasStakeholders();

		String getStakeholders();

		// optional int64 modificacao = 10;
		boolean hasModificacao();

		long getModificacao();

		// optional int32 subarea_id = 11;
		boolean hasSubareaId();

		int getSubareaId();

		// optional .MobiPETIC.Questionario questionario = 12;
		boolean hasQuestionario();

		br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario getQuestionario();

		br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.QuestionarioOrBuilder getQuestionarioOrBuilder();
	}

	public static final class Processo extends
			com.google.protobuf.GeneratedMessage implements ProcessoOrBuilder {
		// Use Processo.newBuilder() to construct.
		private Processo(Builder builder) {
			super(builder);
		}

		private Processo(boolean noInit) {
		}

		private static final Processo defaultInstance;

		public static Processo getDefaultInstance() {
			return defaultInstance;
		}

		public Processo getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.internal_static_MobiPETIC_Processo_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.internal_static_MobiPETIC_Processo_fieldAccessorTable;
		}

		private int bitField0_;
		// required string id = 1;
		public static final int ID_FIELD_NUMBER = 1;
		private java.lang.Object id_;

		public boolean hasId() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public String getId() {
			java.lang.Object ref = id_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					id_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getIdBytes() {
			java.lang.Object ref = id_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				id_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required string nome = 2;
		public static final int NOME_FIELD_NUMBER = 2;
		private java.lang.Object nome_;

		public boolean hasNome() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public String getNome() {
			java.lang.Object ref = nome_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					nome_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getNomeBytes() {
			java.lang.Object ref = nome_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				nome_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional bool e_prioritario = 3;
		public static final int E_PRIORITARIO_FIELD_NUMBER = 3;
		private boolean ePrioritario_;

		public boolean hasEPrioritario() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		public boolean getEPrioritario() {
			return ePrioritario_;
		}

		// optional bool prioridade_def = 4;
		public static final int PRIORIDADE_DEF_FIELD_NUMBER = 4;
		private boolean prioridadeDef_;

		public boolean hasPrioridadeDef() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		public boolean getPrioridadeDef() {
			return prioridadeDef_;
		}

		// optional string descricao = 5;
		public static final int DESCRICAO_FIELD_NUMBER = 5;
		private java.lang.Object descricao_;

		public boolean hasDescricao() {
			return ((bitField0_ & 0x00000010) == 0x00000010);
		}

		public String getDescricao() {
			java.lang.Object ref = descricao_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					descricao_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getDescricaoBytes() {
			java.lang.Object ref = descricao_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				descricao_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional string entradas = 6;
		public static final int ENTRADAS_FIELD_NUMBER = 6;
		private java.lang.Object entradas_;

		public boolean hasEntradas() {
			return ((bitField0_ & 0x00000020) == 0x00000020);
		}

		public String getEntradas() {
			java.lang.Object ref = entradas_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					entradas_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getEntradasBytes() {
			java.lang.Object ref = entradas_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				entradas_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional string saidas = 7;
		public static final int SAIDAS_FIELD_NUMBER = 7;
		private java.lang.Object saidas_;

		public boolean hasSaidas() {
			return ((bitField0_ & 0x00000040) == 0x00000040);
		}

		public String getSaidas() {
			java.lang.Object ref = saidas_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					saidas_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getSaidasBytes() {
			java.lang.Object ref = saidas_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				saidas_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional string responsavel = 8;
		public static final int RESPONSAVEL_FIELD_NUMBER = 8;
		private java.lang.Object responsavel_;

		public boolean hasResponsavel() {
			return ((bitField0_ & 0x00000080) == 0x00000080);
		}

		public String getResponsavel() {
			java.lang.Object ref = responsavel_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					responsavel_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getResponsavelBytes() {
			java.lang.Object ref = responsavel_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				responsavel_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional string stakeholders = 9;
		public static final int STAKEHOLDERS_FIELD_NUMBER = 9;
		private java.lang.Object stakeholders_;

		public boolean hasStakeholders() {
			return ((bitField0_ & 0x00000100) == 0x00000100);
		}

		public String getStakeholders() {
			java.lang.Object ref = stakeholders_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					stakeholders_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getStakeholdersBytes() {
			java.lang.Object ref = stakeholders_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				stakeholders_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional int64 modificacao = 10;
		public static final int MODIFICACAO_FIELD_NUMBER = 10;
		private long modificacao_;

		public boolean hasModificacao() {
			return ((bitField0_ & 0x00000200) == 0x00000200);
		}

		public long getModificacao() {
			return modificacao_;
		}

		// optional int32 subarea_id = 11;
		public static final int SUBAREA_ID_FIELD_NUMBER = 11;
		private int subareaId_;

		public boolean hasSubareaId() {
			return ((bitField0_ & 0x00000400) == 0x00000400);
		}

		public int getSubareaId() {
			return subareaId_;
		}

		// optional .MobiPETIC.Questionario questionario = 12;
		public static final int QUESTIONARIO_FIELD_NUMBER = 12;
		private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario questionario_;

		public boolean hasQuestionario() {
			return ((bitField0_ & 0x00000800) == 0x00000800);
		}

		public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario getQuestionario() {
			return questionario_;
		}

		public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.QuestionarioOrBuilder getQuestionarioOrBuilder() {
			return questionario_;
		}

		private void initFields() {
			id_ = "";
			nome_ = "";
			ePrioritario_ = false;
			prioridadeDef_ = false;
			descricao_ = "";
			entradas_ = "";
			saidas_ = "";
			responsavel_ = "";
			stakeholders_ = "";
			modificacao_ = 0L;
			subareaId_ = 0;
			questionario_ = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario
					.getDefaultInstance();
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasNome()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getIdBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getNomeBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeBool(3, ePrioritario_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeBool(4, prioridadeDef_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				output.writeBytes(5, getDescricaoBytes());
			}
			if (((bitField0_ & 0x00000020) == 0x00000020)) {
				output.writeBytes(6, getEntradasBytes());
			}
			if (((bitField0_ & 0x00000040) == 0x00000040)) {
				output.writeBytes(7, getSaidasBytes());
			}
			if (((bitField0_ & 0x00000080) == 0x00000080)) {
				output.writeBytes(8, getResponsavelBytes());
			}
			if (((bitField0_ & 0x00000100) == 0x00000100)) {
				output.writeBytes(9, getStakeholdersBytes());
			}
			if (((bitField0_ & 0x00000200) == 0x00000200)) {
				output.writeInt64(10, modificacao_);
			}
			if (((bitField0_ & 0x00000400) == 0x00000400)) {
				output.writeInt32(11, subareaId_);
			}
			if (((bitField0_ & 0x00000800) == 0x00000800)) {
				output.writeMessage(12, questionario_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						1, getIdBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						2, getNomeBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeBoolSize(
						3, ePrioritario_);
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeBoolSize(
						4, prioridadeDef_);
			}
			if (((bitField0_ & 0x00000010) == 0x00000010)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						5, getDescricaoBytes());
			}
			if (((bitField0_ & 0x00000020) == 0x00000020)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						6, getEntradasBytes());
			}
			if (((bitField0_ & 0x00000040) == 0x00000040)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						7, getSaidasBytes());
			}
			if (((bitField0_ & 0x00000080) == 0x00000080)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						8, getResponsavelBytes());
			}
			if (((bitField0_ & 0x00000100) == 0x00000100)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						9, getStakeholdersBytes());
			}
			if (((bitField0_ & 0x00000200) == 0x00000200)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(
						10, modificacao_);
			}
			if (((bitField0_ & 0x00000400) == 0x00000400)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						11, subareaId_);
			}
			if (((bitField0_ & 0x00000800) == 0x00000800)) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(12, questionario_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.ProcessoOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.internal_static_MobiPETIC_Processo_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.internal_static_MobiPETIC_Processo_fieldAccessorTable;
			}

			// Construct using
			// br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getQuestionarioFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				id_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				nome_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				ePrioritario_ = false;
				bitField0_ = (bitField0_ & ~0x00000004);
				prioridadeDef_ = false;
				bitField0_ = (bitField0_ & ~0x00000008);
				descricao_ = "";
				bitField0_ = (bitField0_ & ~0x00000010);
				entradas_ = "";
				bitField0_ = (bitField0_ & ~0x00000020);
				saidas_ = "";
				bitField0_ = (bitField0_ & ~0x00000040);
				responsavel_ = "";
				bitField0_ = (bitField0_ & ~0x00000080);
				stakeholders_ = "";
				bitField0_ = (bitField0_ & ~0x00000100);
				modificacao_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000200);
				subareaId_ = 0;
				bitField0_ = (bitField0_ & ~0x00000400);
				if (questionarioBuilder_ == null) {
					questionario_ = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario
							.getDefaultInstance();
				} else {
					questionarioBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000800);
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo
						.getDescriptor();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo getDefaultInstanceForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo
						.getDefaultInstance();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo build() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo buildPartial() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo result = new br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.id_ = id_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.nome_ = nome_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.ePrioritario_ = ePrioritario_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.prioridadeDef_ = prioridadeDef_;
				if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
					to_bitField0_ |= 0x00000010;
				}
				result.descricao_ = descricao_;
				if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
					to_bitField0_ |= 0x00000020;
				}
				result.entradas_ = entradas_;
				if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
					to_bitField0_ |= 0x00000040;
				}
				result.saidas_ = saidas_;
				if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
					to_bitField0_ |= 0x00000080;
				}
				result.responsavel_ = responsavel_;
				if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
					to_bitField0_ |= 0x00000100;
				}
				result.stakeholders_ = stakeholders_;
				if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
					to_bitField0_ |= 0x00000200;
				}
				result.modificacao_ = modificacao_;
				if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
					to_bitField0_ |= 0x00000400;
				}
				result.subareaId_ = subareaId_;
				if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
					to_bitField0_ |= 0x00000800;
				}
				if (questionarioBuilder_ == null) {
					result.questionario_ = questionario_;
				} else {
					result.questionario_ = questionarioBuilder_.build();
				}
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo) {
					return mergeFrom((br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo other) {
				if (other == br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo
						.getDefaultInstance())
					return this;
				if (other.hasId()) {
					setId(other.getId());
				}
				if (other.hasNome()) {
					setNome(other.getNome());
				}
				if (other.hasEPrioritario()) {
					setEPrioritario(other.getEPrioritario());
				}
				if (other.hasPrioridadeDef()) {
					setPrioridadeDef(other.getPrioridadeDef());
				}
				if (other.hasDescricao()) {
					setDescricao(other.getDescricao());
				}
				if (other.hasEntradas()) {
					setEntradas(other.getEntradas());
				}
				if (other.hasSaidas()) {
					setSaidas(other.getSaidas());
				}
				if (other.hasResponsavel()) {
					setResponsavel(other.getResponsavel());
				}
				if (other.hasStakeholders()) {
					setStakeholders(other.getStakeholders());
				}
				if (other.hasModificacao()) {
					setModificacao(other.getModificacao());
				}
				if (other.hasSubareaId()) {
					setSubareaId(other.getSubareaId());
				}
				if (other.hasQuestionario()) {
					mergeQuestionario(other.getQuestionario());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public final boolean isInitialized() {
				if (!hasId()) {

					return false;
				}
				if (!hasNome()) {

					return false;
				}
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						bitField0_ |= 0x00000001;
						id_ = input.readBytes();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						nome_ = input.readBytes();
						break;
					}
					case 24: {
						bitField0_ |= 0x00000004;
						ePrioritario_ = input.readBool();
						break;
					}
					case 32: {
						bitField0_ |= 0x00000008;
						prioridadeDef_ = input.readBool();
						break;
					}
					case 42: {
						bitField0_ |= 0x00000010;
						descricao_ = input.readBytes();
						break;
					}
					case 50: {
						bitField0_ |= 0x00000020;
						entradas_ = input.readBytes();
						break;
					}
					case 58: {
						bitField0_ |= 0x00000040;
						saidas_ = input.readBytes();
						break;
					}
					case 66: {
						bitField0_ |= 0x00000080;
						responsavel_ = input.readBytes();
						break;
					}
					case 74: {
						bitField0_ |= 0x00000100;
						stakeholders_ = input.readBytes();
						break;
					}
					case 80: {
						bitField0_ |= 0x00000200;
						modificacao_ = input.readInt64();
						break;
					}
					case 88: {
						bitField0_ |= 0x00000400;
						subareaId_ = input.readInt32();
						break;
					}
					case 98: {
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario.Builder subBuilder = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario
								.newBuilder();
						if (hasQuestionario()) {
							subBuilder.mergeFrom(getQuestionario());
						}
						input.readMessage(subBuilder, extensionRegistry);
						setQuestionario(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required string id = 1;
			private java.lang.Object id_ = "";

			public boolean hasId() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public String getId() {
				java.lang.Object ref = id_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					id_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setId(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				id_ = value;
				onChanged();
				return this;
			}

			public Builder clearId() {
				bitField0_ = (bitField0_ & ~0x00000001);
				id_ = getDefaultInstance().getId();
				onChanged();
				return this;
			}

			void setId(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000001;
				id_ = value;
				onChanged();
			}

			// required string nome = 2;
			private java.lang.Object nome_ = "";

			public boolean hasNome() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public String getNome() {
				java.lang.Object ref = nome_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					nome_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setNome(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				nome_ = value;
				onChanged();
				return this;
			}

			public Builder clearNome() {
				bitField0_ = (bitField0_ & ~0x00000002);
				nome_ = getDefaultInstance().getNome();
				onChanged();
				return this;
			}

			void setNome(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000002;
				nome_ = value;
				onChanged();
			}

			// optional bool e_prioritario = 3;
			private boolean ePrioritario_;

			public boolean hasEPrioritario() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			public boolean getEPrioritario() {
				return ePrioritario_;
			}

			public Builder setEPrioritario(boolean value) {
				bitField0_ |= 0x00000004;
				ePrioritario_ = value;
				onChanged();
				return this;
			}

			public Builder clearEPrioritario() {
				bitField0_ = (bitField0_ & ~0x00000004);
				ePrioritario_ = false;
				onChanged();
				return this;
			}

			// optional bool prioridade_def = 4;
			private boolean prioridadeDef_;

			public boolean hasPrioridadeDef() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			public boolean getPrioridadeDef() {
				return prioridadeDef_;
			}

			public Builder setPrioridadeDef(boolean value) {
				bitField0_ |= 0x00000008;
				prioridadeDef_ = value;
				onChanged();
				return this;
			}

			public Builder clearPrioridadeDef() {
				bitField0_ = (bitField0_ & ~0x00000008);
				prioridadeDef_ = false;
				onChanged();
				return this;
			}

			// optional string descricao = 5;
			private java.lang.Object descricao_ = "";

			public boolean hasDescricao() {
				return ((bitField0_ & 0x00000010) == 0x00000010);
			}

			public String getDescricao() {
				java.lang.Object ref = descricao_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					descricao_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setDescricao(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000010;
				descricao_ = value;
				onChanged();
				return this;
			}

			public Builder clearDescricao() {
				bitField0_ = (bitField0_ & ~0x00000010);
				descricao_ = getDefaultInstance().getDescricao();
				onChanged();
				return this;
			}

			void setDescricao(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000010;
				descricao_ = value;
				onChanged();
			}

			// optional string entradas = 6;
			private java.lang.Object entradas_ = "";

			public boolean hasEntradas() {
				return ((bitField0_ & 0x00000020) == 0x00000020);
			}

			public String getEntradas() {
				java.lang.Object ref = entradas_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					entradas_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setEntradas(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000020;
				entradas_ = value;
				onChanged();
				return this;
			}

			public Builder clearEntradas() {
				bitField0_ = (bitField0_ & ~0x00000020);
				entradas_ = getDefaultInstance().getEntradas();
				onChanged();
				return this;
			}

			void setEntradas(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000020;
				entradas_ = value;
				onChanged();
			}

			// optional string saidas = 7;
			private java.lang.Object saidas_ = "";

			public boolean hasSaidas() {
				return ((bitField0_ & 0x00000040) == 0x00000040);
			}

			public String getSaidas() {
				java.lang.Object ref = saidas_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					saidas_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setSaidas(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000040;
				saidas_ = value;
				onChanged();
				return this;
			}

			public Builder clearSaidas() {
				bitField0_ = (bitField0_ & ~0x00000040);
				saidas_ = getDefaultInstance().getSaidas();
				onChanged();
				return this;
			}

			void setSaidas(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000040;
				saidas_ = value;
				onChanged();
			}

			// optional string responsavel = 8;
			private java.lang.Object responsavel_ = "";

			public boolean hasResponsavel() {
				return ((bitField0_ & 0x00000080) == 0x00000080);
			}

			public String getResponsavel() {
				java.lang.Object ref = responsavel_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					responsavel_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setResponsavel(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000080;
				responsavel_ = value;
				onChanged();
				return this;
			}

			public Builder clearResponsavel() {
				bitField0_ = (bitField0_ & ~0x00000080);
				responsavel_ = getDefaultInstance().getResponsavel();
				onChanged();
				return this;
			}

			void setResponsavel(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000080;
				responsavel_ = value;
				onChanged();
			}

			// optional string stakeholders = 9;
			private java.lang.Object stakeholders_ = "";

			public boolean hasStakeholders() {
				return ((bitField0_ & 0x00000100) == 0x00000100);
			}

			public String getStakeholders() {
				java.lang.Object ref = stakeholders_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					stakeholders_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setStakeholders(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000100;
				stakeholders_ = value;
				onChanged();
				return this;
			}

			public Builder clearStakeholders() {
				bitField0_ = (bitField0_ & ~0x00000100);
				stakeholders_ = getDefaultInstance().getStakeholders();
				onChanged();
				return this;
			}

			void setStakeholders(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000100;
				stakeholders_ = value;
				onChanged();
			}

			// optional int64 modificacao = 10;
			private long modificacao_;

			public boolean hasModificacao() {
				return ((bitField0_ & 0x00000200) == 0x00000200);
			}

			public long getModificacao() {
				return modificacao_;
			}

			public Builder setModificacao(long value) {
				bitField0_ |= 0x00000200;
				modificacao_ = value;
				onChanged();
				return this;
			}

			public Builder clearModificacao() {
				bitField0_ = (bitField0_ & ~0x00000200);
				modificacao_ = 0L;
				onChanged();
				return this;
			}

			// optional int32 subarea_id = 11;
			private int subareaId_;

			public boolean hasSubareaId() {
				return ((bitField0_ & 0x00000400) == 0x00000400);
			}

			public int getSubareaId() {
				return subareaId_;
			}

			public Builder setSubareaId(int value) {
				bitField0_ |= 0x00000400;
				subareaId_ = value;
				onChanged();
				return this;
			}

			public Builder clearSubareaId() {
				bitField0_ = (bitField0_ & ~0x00000400);
				subareaId_ = 0;
				onChanged();
				return this;
			}

			// optional .MobiPETIC.Questionario questionario = 12;
			private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario questionario_ = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario
					.getDefaultInstance();
			private com.google.protobuf.SingleFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.QuestionarioOrBuilder> questionarioBuilder_;

			public boolean hasQuestionario() {
				return ((bitField0_ & 0x00000800) == 0x00000800);
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario getQuestionario() {
				if (questionarioBuilder_ == null) {
					return questionario_;
				} else {
					return questionarioBuilder_.getMessage();
				}
			}

			public Builder setQuestionario(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario value) {
				if (questionarioBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					questionario_ = value;
					onChanged();
				} else {
					questionarioBuilder_.setMessage(value);
				}
				bitField0_ |= 0x00000800;
				return this;
			}

			public Builder setQuestionario(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario.Builder builderForValue) {
				if (questionarioBuilder_ == null) {
					questionario_ = builderForValue.build();
					onChanged();
				} else {
					questionarioBuilder_.setMessage(builderForValue.build());
				}
				bitField0_ |= 0x00000800;
				return this;
			}

			public Builder mergeQuestionario(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario value) {
				if (questionarioBuilder_ == null) {
					if (((bitField0_ & 0x00000800) == 0x00000800)
							&& questionario_ != br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario
									.getDefaultInstance()) {
						questionario_ = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario
								.newBuilder(questionario_).mergeFrom(value)
								.buildPartial();
					} else {
						questionario_ = value;
					}
					onChanged();
				} else {
					questionarioBuilder_.mergeFrom(value);
				}
				bitField0_ |= 0x00000800;
				return this;
			}

			public Builder clearQuestionario() {
				if (questionarioBuilder_ == null) {
					questionario_ = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario
							.getDefaultInstance();
					onChanged();
				} else {
					questionarioBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000800);
				return this;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario.Builder getQuestionarioBuilder() {
				bitField0_ |= 0x00000800;
				onChanged();
				return getQuestionarioFieldBuilder().getBuilder();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.QuestionarioOrBuilder getQuestionarioOrBuilder() {
				if (questionarioBuilder_ != null) {
					return questionarioBuilder_.getMessageOrBuilder();
				} else {
					return questionario_;
				}
			}

			private com.google.protobuf.SingleFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.QuestionarioOrBuilder> getQuestionarioFieldBuilder() {
				if (questionarioBuilder_ == null) {
					questionarioBuilder_ = new com.google.protobuf.SingleFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.QuestionarioOrBuilder>(
							questionario_, getParentForChildren(), isClean());
					questionario_ = null;
				}
				return questionarioBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:MobiPETIC.Processo)
		}

		static {
			defaultInstance = new Processo(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:MobiPETIC.Processo)
	}

	public interface QuestionarioOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// optional int64 modificacao = 1;
		boolean hasModificacao();

		long getModificacao();

		// optional string editor = 2;
		boolean hasEditor();

		String getEditor();

		// optional .MobiPETIC.Maturidade maturidade = 3;
		boolean hasMaturidade();

		br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade getMaturidade();

		// optional .MobiPETIC.Maturidade maturidade_ant = 4;
		boolean hasMaturidadeAnt();

		br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade getMaturidadeAnt();
	}

	public static final class Questionario extends
			com.google.protobuf.GeneratedMessage implements
			QuestionarioOrBuilder {
		// Use Questionario.newBuilder() to construct.
		private Questionario(Builder builder) {
			super(builder);
		}

		private Questionario(boolean noInit) {
		}

		private static final Questionario defaultInstance;

		public static Questionario getDefaultInstance() {
			return defaultInstance;
		}

		public Questionario getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.internal_static_MobiPETIC_Questionario_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.internal_static_MobiPETIC_Questionario_fieldAccessorTable;
		}

		private int bitField0_;
		// optional int64 modificacao = 1;
		public static final int MODIFICACAO_FIELD_NUMBER = 1;
		private long modificacao_;

		public boolean hasModificacao() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public long getModificacao() {
			return modificacao_;
		}

		// optional string editor = 2;
		public static final int EDITOR_FIELD_NUMBER = 2;
		private java.lang.Object editor_;

		public boolean hasEditor() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public String getEditor() {
			java.lang.Object ref = editor_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					editor_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getEditorBytes() {
			java.lang.Object ref = editor_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				editor_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional .MobiPETIC.Maturidade maturidade = 3;
		public static final int MATURIDADE_FIELD_NUMBER = 3;
		private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade maturidade_;

		public boolean hasMaturidade() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade getMaturidade() {
			return maturidade_;
		}

		// optional .MobiPETIC.Maturidade maturidade_ant = 4;
		public static final int MATURIDADE_ANT_FIELD_NUMBER = 4;
		private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade maturidadeAnt_;

		public boolean hasMaturidadeAnt() {
			return ((bitField0_ & 0x00000008) == 0x00000008);
		}

		public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade getMaturidadeAnt() {
			return maturidadeAnt_;
		}

		private void initFields() {
			modificacao_ = 0L;
			editor_ = "";
			maturidade_ = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade.INDEFINIDA;
			maturidadeAnt_ = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade.INDEFINIDA;
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt64(1, modificacao_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getEditorBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeEnum(3, maturidade_.getNumber());
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				output.writeEnum(4, maturidadeAnt_.getNumber());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(
						1, modificacao_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						2, getEditorBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeEnumSize(
						3, maturidade_.getNumber());
			}
			if (((bitField0_ & 0x00000008) == 0x00000008)) {
				size += com.google.protobuf.CodedOutputStream.computeEnumSize(
						4, maturidadeAnt_.getNumber());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.QuestionarioOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.internal_static_MobiPETIC_Questionario_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.internal_static_MobiPETIC_Questionario_fieldAccessorTable;
			}

			// Construct using
			// br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				modificacao_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000001);
				editor_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				maturidade_ = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade.INDEFINIDA;
				bitField0_ = (bitField0_ & ~0x00000004);
				maturidadeAnt_ = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade.INDEFINIDA;
				bitField0_ = (bitField0_ & ~0x00000008);
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario
						.getDescriptor();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario getDefaultInstanceForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario
						.getDefaultInstance();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario build() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario buildPartial() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario result = new br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.modificacao_ = modificacao_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.editor_ = editor_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.maturidade_ = maturidade_;
				if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
					to_bitField0_ |= 0x00000008;
				}
				result.maturidadeAnt_ = maturidadeAnt_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario) {
					return mergeFrom((br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario other) {
				if (other == br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario
						.getDefaultInstance())
					return this;
				if (other.hasModificacao()) {
					setModificacao(other.getModificacao());
				}
				if (other.hasEditor()) {
					setEditor(other.getEditor());
				}
				if (other.hasMaturidade()) {
					setMaturidade(other.getMaturidade());
				}
				if (other.hasMaturidadeAnt()) {
					setMaturidadeAnt(other.getMaturidadeAnt());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						modificacao_ = input.readInt64();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						editor_ = input.readBytes();
						break;
					}
					case 24: {
						int rawValue = input.readEnum();
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade value = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade
								.valueOf(rawValue);
						if (value == null) {
							unknownFields.mergeVarintField(3, rawValue);
						} else {
							bitField0_ |= 0x00000004;
							maturidade_ = value;
						}
						break;
					}
					case 32: {
						int rawValue = input.readEnum();
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade value = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade
								.valueOf(rawValue);
						if (value == null) {
							unknownFields.mergeVarintField(4, rawValue);
						} else {
							bitField0_ |= 0x00000008;
							maturidadeAnt_ = value;
						}
						break;
					}
					}
				}
			}

			private int bitField0_;

			// optional int64 modificacao = 1;
			private long modificacao_;

			public boolean hasModificacao() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public long getModificacao() {
				return modificacao_;
			}

			public Builder setModificacao(long value) {
				bitField0_ |= 0x00000001;
				modificacao_ = value;
				onChanged();
				return this;
			}

			public Builder clearModificacao() {
				bitField0_ = (bitField0_ & ~0x00000001);
				modificacao_ = 0L;
				onChanged();
				return this;
			}

			// optional string editor = 2;
			private java.lang.Object editor_ = "";

			public boolean hasEditor() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public String getEditor() {
				java.lang.Object ref = editor_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					editor_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setEditor(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				editor_ = value;
				onChanged();
				return this;
			}

			public Builder clearEditor() {
				bitField0_ = (bitField0_ & ~0x00000002);
				editor_ = getDefaultInstance().getEditor();
				onChanged();
				return this;
			}

			void setEditor(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000002;
				editor_ = value;
				onChanged();
			}

			// optional .MobiPETIC.Maturidade maturidade = 3;
			private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade maturidade_ = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade.INDEFINIDA;

			public boolean hasMaturidade() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade getMaturidade() {
				return maturidade_;
			}

			public Builder setMaturidade(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				maturidade_ = value;
				onChanged();
				return this;
			}

			public Builder clearMaturidade() {
				bitField0_ = (bitField0_ & ~0x00000004);
				maturidade_ = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade.INDEFINIDA;
				onChanged();
				return this;
			}

			// optional .MobiPETIC.Maturidade maturidade_ant = 4;
			private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade maturidadeAnt_ = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade.INDEFINIDA;

			public boolean hasMaturidadeAnt() {
				return ((bitField0_ & 0x00000008) == 0x00000008);
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade getMaturidadeAnt() {
				return maturidadeAnt_;
			}

			public Builder setMaturidadeAnt(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000008;
				maturidadeAnt_ = value;
				onChanged();
				return this;
			}

			public Builder clearMaturidadeAnt() {
				bitField0_ = (bitField0_ & ~0x00000008);
				maturidadeAnt_ = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Maturidade.INDEFINIDA;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:MobiPETIC.Questionario)
		}

		static {
			defaultInstance = new Questionario(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:MobiPETIC.Questionario)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_MobiPETIC_Processos_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_MobiPETIC_Processos_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_MobiPETIC_Processo_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_MobiPETIC_Processo_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_MobiPETIC_Questionario_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_MobiPETIC_Questionario_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = {
				"\n\023Processosfile.proto\022\tMobiPETIC\"2\n\tProc"
						+ "essos\022%\n\010processo\030\001 \003(\0132\023.MobiPETIC.Proc"
						+ "esso\"\213\002\n\010Processo\022\n\n\002id\030\001 \002(\t\022\014\n\004nome\030\002 "
						+ "\002(\t\022\025\n\re_prioritario\030\003 \001(\010\022\026\n\016prioridade"
						+ "_def\030\004 \001(\010\022\021\n\tdescricao\030\005 \001(\t\022\020\n\010entrada"
						+ "s\030\006 \001(\t\022\016\n\006saidas\030\007 \001(\t\022\023\n\013responsavel\030\010"
						+ " \001(\t\022\024\n\014stakeholders\030\t \001(\t\022\023\n\013modificaca"
						+ "o\030\n \001(\003\022\022\n\nsubarea_id\030\013 \001(\005\022-\n\014questiona"
						+ "rio\030\014 \001(\0132\027.MobiPETIC.Questionario\"\215\001\n\014Q"
						+ "uestionario\022\023\n\013modificacao\030\001 \001(\003\022\016\n\006edit",
				"or\030\002 \001(\t\022)\n\nmaturidade\030\003 \001(\0162\025.MobiPETIC"
						+ ".Maturidade\022-\n\016maturidade_ant\030\004 \001(\0162\025.Mo"
						+ "biPETIC.Maturidade*h\n\nMaturidade\022\016\n\nINDE"
						+ "FINIDA\020\000\022\017\n\013INEXISTENTE\020\001\022\n\n\006MINIMO\020\002\022\n\n"
						+ "\006SEGURO\020\003\022\020\n\014SATISFATORIO\020\004\022\017\n\013ESTADOIDE"
						+ "AL\020\005BG\n4br.ufs.dcomp.gpes.peticwizard.pr"
						+ "esentation.MobiPETICB\017ProcessosProtos" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_MobiPETIC_Processos_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_MobiPETIC_Processos_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_MobiPETIC_Processos_descriptor,
						new java.lang.String[] { "Processo", },
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos.class,
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processos.Builder.class);
				internal_static_MobiPETIC_Processo_descriptor = getDescriptor()
						.getMessageTypes().get(1);
				internal_static_MobiPETIC_Processo_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_MobiPETIC_Processo_descriptor,
						new java.lang.String[] { "Id", "Nome", "EPrioritario",
								"PrioridadeDef", "Descricao", "Entradas",
								"Saidas", "Responsavel", "Stakeholders",
								"Modificacao", "SubareaId", "Questionario", },
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo.class,
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Processo.Builder.class);
				internal_static_MobiPETIC_Questionario_descriptor = getDescriptor()
						.getMessageTypes().get(2);
				internal_static_MobiPETIC_Questionario_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_MobiPETIC_Questionario_descriptor,
						new java.lang.String[] { "Modificacao", "Editor",
								"Maturidade", "MaturidadeAnt", },
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario.class,
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.ProcessosProtos.Questionario.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
