// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Subareasfile.proto

package br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC;

public final class SubareasProtos {
	private SubareasProtos() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface SubareasOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// repeated .MobiPETIC.Subarea subarea = 1;
		java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea> getSubareaList();

		br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea getSubarea(
				int index);

		int getSubareaCount();

		java.util.List<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.SubareaOrBuilder> getSubareaOrBuilderList();

		br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.SubareaOrBuilder getSubareaOrBuilder(
				int index);
	}

	public static final class Subareas extends
			com.google.protobuf.GeneratedMessage implements SubareasOrBuilder {
		// Use Subareas.newBuilder() to construct.
		private Subareas(Builder builder) {
			super(builder);
		}

		private Subareas(boolean noInit) {
		}

		private static final Subareas defaultInstance;

		public static Subareas getDefaultInstance() {
			return defaultInstance;
		}

		public Subareas getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.internal_static_MobiPETIC_Subareas_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.internal_static_MobiPETIC_Subareas_fieldAccessorTable;
		}

		// repeated .MobiPETIC.Subarea subarea = 1;
		public static final int SUBAREA_FIELD_NUMBER = 1;
		private java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea> subarea_;

		public java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea> getSubareaList() {
			return subarea_;
		}

		public java.util.List<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.SubareaOrBuilder> getSubareaOrBuilderList() {
			return subarea_;
		}

		public int getSubareaCount() {
			return subarea_.size();
		}

		public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea getSubarea(
				int index) {
			return subarea_.get(index);
		}

		public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.SubareaOrBuilder getSubareaOrBuilder(
				int index) {
			return subarea_.get(index);
		}

		private void initFields() {
			subarea_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			for (int i = 0; i < getSubareaCount(); i++) {
				if (!getSubarea(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < subarea_.size(); i++) {
				output.writeMessage(1, subarea_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < subarea_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(1, subarea_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.SubareasOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.internal_static_MobiPETIC_Subareas_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.internal_static_MobiPETIC_Subareas_fieldAccessorTable;
			}

			// Construct using
			// br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getSubareaFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				if (subareaBuilder_ == null) {
					subarea_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					subareaBuilder_.clear();
				}
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas
						.getDescriptor();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas getDefaultInstanceForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas
						.getDefaultInstance();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas build() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas buildPartial() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas result = new br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas(
						this);
				int from_bitField0_ = bitField0_;
				if (subareaBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						subarea_ = java.util.Collections
								.unmodifiableList(subarea_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.subarea_ = subarea_;
				} else {
					result.subarea_ = subareaBuilder_.build();
				}
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas) {
					return mergeFrom((br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas other) {
				if (other == br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas
						.getDefaultInstance())
					return this;
				if (subareaBuilder_ == null) {
					if (!other.subarea_.isEmpty()) {
						if (subarea_.isEmpty()) {
							subarea_ = other.subarea_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureSubareaIsMutable();
							subarea_.addAll(other.subarea_);
						}
						onChanged();
					}
				} else {
					if (!other.subarea_.isEmpty()) {
						if (subareaBuilder_.isEmpty()) {
							subareaBuilder_.dispose();
							subareaBuilder_ = null;
							subarea_ = other.subarea_;
							bitField0_ = (bitField0_ & ~0x00000001);
							subareaBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getSubareaFieldBuilder()
									: null;
						} else {
							subareaBuilder_.addAllMessages(other.subarea_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public final boolean isInitialized() {
				for (int i = 0; i < getSubareaCount(); i++) {
					if (!getSubarea(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea.Builder subBuilder = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea
								.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addSubarea(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// repeated .MobiPETIC.Subarea subarea = 1;
			private java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea> subarea_ = java.util.Collections
					.emptyList();

			private void ensureSubareaIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					subarea_ = new java.util.ArrayList<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea>(
							subarea_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.SubareaOrBuilder> subareaBuilder_;

			public java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea> getSubareaList() {
				if (subareaBuilder_ == null) {
					return java.util.Collections.unmodifiableList(subarea_);
				} else {
					return subareaBuilder_.getMessageList();
				}
			}

			public int getSubareaCount() {
				if (subareaBuilder_ == null) {
					return subarea_.size();
				} else {
					return subareaBuilder_.getCount();
				}
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea getSubarea(
					int index) {
				if (subareaBuilder_ == null) {
					return subarea_.get(index);
				} else {
					return subareaBuilder_.getMessage(index);
				}
			}

			public Builder setSubarea(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea value) {
				if (subareaBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureSubareaIsMutable();
					subarea_.set(index, value);
					onChanged();
				} else {
					subareaBuilder_.setMessage(index, value);
				}
				return this;
			}

			public Builder setSubarea(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea.Builder builderForValue) {
				if (subareaBuilder_ == null) {
					ensureSubareaIsMutable();
					subarea_.set(index, builderForValue.build());
					onChanged();
				} else {
					subareaBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addSubarea(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea value) {
				if (subareaBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureSubareaIsMutable();
					subarea_.add(value);
					onChanged();
				} else {
					subareaBuilder_.addMessage(value);
				}
				return this;
			}

			public Builder addSubarea(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea value) {
				if (subareaBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureSubareaIsMutable();
					subarea_.add(index, value);
					onChanged();
				} else {
					subareaBuilder_.addMessage(index, value);
				}
				return this;
			}

			public Builder addSubarea(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea.Builder builderForValue) {
				if (subareaBuilder_ == null) {
					ensureSubareaIsMutable();
					subarea_.add(builderForValue.build());
					onChanged();
				} else {
					subareaBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			public Builder addSubarea(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea.Builder builderForValue) {
				if (subareaBuilder_ == null) {
					ensureSubareaIsMutable();
					subarea_.add(index, builderForValue.build());
					onChanged();
				} else {
					subareaBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addAllSubarea(
					java.lang.Iterable<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea> values) {
				if (subareaBuilder_ == null) {
					ensureSubareaIsMutable();
					super.addAll(values, subarea_);
					onChanged();
				} else {
					subareaBuilder_.addAllMessages(values);
				}
				return this;
			}

			public Builder clearSubarea() {
				if (subareaBuilder_ == null) {
					subarea_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					subareaBuilder_.clear();
				}
				return this;
			}

			public Builder removeSubarea(int index) {
				if (subareaBuilder_ == null) {
					ensureSubareaIsMutable();
					subarea_.remove(index);
					onChanged();
				} else {
					subareaBuilder_.remove(index);
				}
				return this;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea.Builder getSubareaBuilder(
					int index) {
				return getSubareaFieldBuilder().getBuilder(index);
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.SubareaOrBuilder getSubareaOrBuilder(
					int index) {
				if (subareaBuilder_ == null) {
					return subarea_.get(index);
				} else {
					return subareaBuilder_.getMessageOrBuilder(index);
				}
			}

			public java.util.List<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.SubareaOrBuilder> getSubareaOrBuilderList() {
				if (subareaBuilder_ != null) {
					return subareaBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(subarea_);
				}
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea.Builder addSubareaBuilder() {
				return getSubareaFieldBuilder()
						.addBuilder(
								br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea
										.getDefaultInstance());
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea.Builder addSubareaBuilder(
					int index) {
				return getSubareaFieldBuilder()
						.addBuilder(
								index,
								br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea
										.getDefaultInstance());
			}

			public java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea.Builder> getSubareaBuilderList() {
				return getSubareaFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.SubareaOrBuilder> getSubareaFieldBuilder() {
				if (subareaBuilder_ == null) {
					subareaBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.SubareaOrBuilder>(
							subarea_,
							((bitField0_ & 0x00000001) == 0x00000001),
							getParentForChildren(), isClean());
					subarea_ = null;
				}
				return subareaBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:MobiPETIC.Subareas)
		}

		static {
			defaultInstance = new Subareas(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:MobiPETIC.Subareas)
	}

	public interface SubareaOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// required string id = 1;
		boolean hasId();

		String getId();

		// required string nome = 2;
		boolean hasNome();

		String getNome();

		// optional int32 area_id = 3;
		boolean hasAreaId();

		int getAreaId();
	}

	public static final class Subarea extends
			com.google.protobuf.GeneratedMessage implements SubareaOrBuilder {
		// Use Subarea.newBuilder() to construct.
		private Subarea(Builder builder) {
			super(builder);
		}

		private Subarea(boolean noInit) {
		}

		private static final Subarea defaultInstance;

		public static Subarea getDefaultInstance() {
			return defaultInstance;
		}

		public Subarea getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.internal_static_MobiPETIC_Subarea_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.internal_static_MobiPETIC_Subarea_fieldAccessorTable;
		}

		private int bitField0_;
		// required string id = 1;
		public static final int ID_FIELD_NUMBER = 1;
		private java.lang.Object id_;

		public boolean hasId() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public String getId() {
			java.lang.Object ref = id_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					id_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getIdBytes() {
			java.lang.Object ref = id_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				id_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required string nome = 2;
		public static final int NOME_FIELD_NUMBER = 2;
		private java.lang.Object nome_;

		public boolean hasNome() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public String getNome() {
			java.lang.Object ref = nome_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					nome_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getNomeBytes() {
			java.lang.Object ref = nome_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				nome_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional int32 area_id = 3;
		public static final int AREA_ID_FIELD_NUMBER = 3;
		private int areaId_;

		public boolean hasAreaId() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		public int getAreaId() {
			return areaId_;
		}

		private void initFields() {
			id_ = "";
			nome_ = "";
			areaId_ = 0;
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasNome()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getIdBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getNomeBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeInt32(3, areaId_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						1, getIdBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						2, getNomeBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						3, areaId_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.SubareaOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.internal_static_MobiPETIC_Subarea_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.internal_static_MobiPETIC_Subarea_fieldAccessorTable;
			}

			// Construct using
			// br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				id_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				nome_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				areaId_ = 0;
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea
						.getDescriptor();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea getDefaultInstanceForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea
						.getDefaultInstance();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea build() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea buildPartial() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea result = new br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.id_ = id_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.nome_ = nome_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.areaId_ = areaId_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea) {
					return mergeFrom((br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea other) {
				if (other == br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea
						.getDefaultInstance())
					return this;
				if (other.hasId()) {
					setId(other.getId());
				}
				if (other.hasNome()) {
					setNome(other.getNome());
				}
				if (other.hasAreaId()) {
					setAreaId(other.getAreaId());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public final boolean isInitialized() {
				if (!hasId()) {

					return false;
				}
				if (!hasNome()) {

					return false;
				}
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						bitField0_ |= 0x00000001;
						id_ = input.readBytes();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						nome_ = input.readBytes();
						break;
					}
					case 24: {
						bitField0_ |= 0x00000004;
						areaId_ = input.readInt32();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required string id = 1;
			private java.lang.Object id_ = "";

			public boolean hasId() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public String getId() {
				java.lang.Object ref = id_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					id_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setId(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				id_ = value;
				onChanged();
				return this;
			}

			public Builder clearId() {
				bitField0_ = (bitField0_ & ~0x00000001);
				id_ = getDefaultInstance().getId();
				onChanged();
				return this;
			}

			void setId(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000001;
				id_ = value;
				onChanged();
			}

			// required string nome = 2;
			private java.lang.Object nome_ = "";

			public boolean hasNome() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public String getNome() {
				java.lang.Object ref = nome_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					nome_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setNome(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				nome_ = value;
				onChanged();
				return this;
			}

			public Builder clearNome() {
				bitField0_ = (bitField0_ & ~0x00000002);
				nome_ = getDefaultInstance().getNome();
				onChanged();
				return this;
			}

			void setNome(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000002;
				nome_ = value;
				onChanged();
			}

			// optional int32 area_id = 3;
			private int areaId_;

			public boolean hasAreaId() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			public int getAreaId() {
				return areaId_;
			}

			public Builder setAreaId(int value) {
				bitField0_ |= 0x00000004;
				areaId_ = value;
				onChanged();
				return this;
			}

			public Builder clearAreaId() {
				bitField0_ = (bitField0_ & ~0x00000004);
				areaId_ = 0;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:MobiPETIC.Subarea)
		}

		static {
			defaultInstance = new Subarea(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:MobiPETIC.Subarea)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_MobiPETIC_Subareas_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_MobiPETIC_Subareas_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_MobiPETIC_Subarea_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_MobiPETIC_Subarea_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\022Subareasfile.proto\022\tMobiPETIC\"/\n\010Subar"
				+ "eas\022#\n\007subarea\030\001 \003(\0132\022.MobiPETIC.Subarea"
				+ "\"4\n\007Subarea\022\n\n\002id\030\001 \002(\t\022\014\n\004nome\030\002 \002(\t\022\017\n"
				+ "\007area_id\030\003 \001(\005BF\n4br.ufs.dcomp.gpes.peti"
				+ "cwizard.presentation.MobiPETICB\016Subareas" + "Protos" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_MobiPETIC_Subareas_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_MobiPETIC_Subareas_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_MobiPETIC_Subareas_descriptor,
						new java.lang.String[] { "Subarea", },
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas.class,
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subareas.Builder.class);
				internal_static_MobiPETIC_Subarea_descriptor = getDescriptor()
						.getMessageTypes().get(1);
				internal_static_MobiPETIC_Subarea_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_MobiPETIC_Subarea_descriptor,
						new java.lang.String[] { "Id", "Nome", "AreaId", },
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea.class,
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.SubareasProtos.Subarea.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
