// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Areasfile.proto

package br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC;

public final class AreasProtos {
	private AreasProtos() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface AreasOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// repeated .MobiPETIC.Area area = 1;
		java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area> getAreaList();

		br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area getArea(
				int index);

		int getAreaCount();

		java.util.List<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.AreaOrBuilder> getAreaOrBuilderList();

		br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.AreaOrBuilder getAreaOrBuilder(
				int index);
	}

	public static final class Areas extends
			com.google.protobuf.GeneratedMessage implements AreasOrBuilder {
		// Use Areas.newBuilder() to construct.
		private Areas(Builder builder) {
			super(builder);
		}

		private Areas(boolean noInit) {
		}

		private static final Areas defaultInstance;

		public static Areas getDefaultInstance() {
			return defaultInstance;
		}

		public Areas getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.internal_static_MobiPETIC_Areas_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.internal_static_MobiPETIC_Areas_fieldAccessorTable;
		}

		// repeated .MobiPETIC.Area area = 1;
		public static final int AREA_FIELD_NUMBER = 1;
		private java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area> area_;

		public java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area> getAreaList() {
			return area_;
		}

		public java.util.List<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.AreaOrBuilder> getAreaOrBuilderList() {
			return area_;
		}

		public int getAreaCount() {
			return area_.size();
		}

		public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area getArea(
				int index) {
			return area_.get(index);
		}

		public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.AreaOrBuilder getAreaOrBuilder(
				int index) {
			return area_.get(index);
		}

		private void initFields() {
			area_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			for (int i = 0; i < getAreaCount(); i++) {
				if (!getArea(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < area_.size(); i++) {
				output.writeMessage(1, area_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < area_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(1, area_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.AreasOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.internal_static_MobiPETIC_Areas_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.internal_static_MobiPETIC_Areas_fieldAccessorTable;
			}

			// Construct using
			// br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getAreaFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				if (areaBuilder_ == null) {
					area_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					areaBuilder_.clear();
				}
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas
						.getDescriptor();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas getDefaultInstanceForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas
						.getDefaultInstance();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas build() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas buildPartial() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas result = new br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas(
						this);
				int from_bitField0_ = bitField0_;
				if (areaBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						area_ = java.util.Collections.unmodifiableList(area_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.area_ = area_;
				} else {
					result.area_ = areaBuilder_.build();
				}
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas) {
					return mergeFrom((br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas other) {
				if (other == br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas
						.getDefaultInstance())
					return this;
				if (areaBuilder_ == null) {
					if (!other.area_.isEmpty()) {
						if (area_.isEmpty()) {
							area_ = other.area_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureAreaIsMutable();
							area_.addAll(other.area_);
						}
						onChanged();
					}
				} else {
					if (!other.area_.isEmpty()) {
						if (areaBuilder_.isEmpty()) {
							areaBuilder_.dispose();
							areaBuilder_ = null;
							area_ = other.area_;
							bitField0_ = (bitField0_ & ~0x00000001);
							areaBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getAreaFieldBuilder()
									: null;
						} else {
							areaBuilder_.addAllMessages(other.area_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public final boolean isInitialized() {
				for (int i = 0; i < getAreaCount(); i++) {
					if (!getArea(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area.Builder subBuilder = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area
								.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addArea(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// repeated .MobiPETIC.Area area = 1;
			private java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area> area_ = java.util.Collections
					.emptyList();

			private void ensureAreaIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					area_ = new java.util.ArrayList<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area>(
							area_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.AreaOrBuilder> areaBuilder_;

			public java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area> getAreaList() {
				if (areaBuilder_ == null) {
					return java.util.Collections.unmodifiableList(area_);
				} else {
					return areaBuilder_.getMessageList();
				}
			}

			public int getAreaCount() {
				if (areaBuilder_ == null) {
					return area_.size();
				} else {
					return areaBuilder_.getCount();
				}
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area getArea(
					int index) {
				if (areaBuilder_ == null) {
					return area_.get(index);
				} else {
					return areaBuilder_.getMessage(index);
				}
			}

			public Builder setArea(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area value) {
				if (areaBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureAreaIsMutable();
					area_.set(index, value);
					onChanged();
				} else {
					areaBuilder_.setMessage(index, value);
				}
				return this;
			}

			public Builder setArea(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area.Builder builderForValue) {
				if (areaBuilder_ == null) {
					ensureAreaIsMutable();
					area_.set(index, builderForValue.build());
					onChanged();
				} else {
					areaBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addArea(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area value) {
				if (areaBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureAreaIsMutable();
					area_.add(value);
					onChanged();
				} else {
					areaBuilder_.addMessage(value);
				}
				return this;
			}

			public Builder addArea(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area value) {
				if (areaBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureAreaIsMutable();
					area_.add(index, value);
					onChanged();
				} else {
					areaBuilder_.addMessage(index, value);
				}
				return this;
			}

			public Builder addArea(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area.Builder builderForValue) {
				if (areaBuilder_ == null) {
					ensureAreaIsMutable();
					area_.add(builderForValue.build());
					onChanged();
				} else {
					areaBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			public Builder addArea(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area.Builder builderForValue) {
				if (areaBuilder_ == null) {
					ensureAreaIsMutable();
					area_.add(index, builderForValue.build());
					onChanged();
				} else {
					areaBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addAllArea(
					java.lang.Iterable<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area> values) {
				if (areaBuilder_ == null) {
					ensureAreaIsMutable();
					super.addAll(values, area_);
					onChanged();
				} else {
					areaBuilder_.addAllMessages(values);
				}
				return this;
			}

			public Builder clearArea() {
				if (areaBuilder_ == null) {
					area_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					areaBuilder_.clear();
				}
				return this;
			}

			public Builder removeArea(int index) {
				if (areaBuilder_ == null) {
					ensureAreaIsMutable();
					area_.remove(index);
					onChanged();
				} else {
					areaBuilder_.remove(index);
				}
				return this;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area.Builder getAreaBuilder(
					int index) {
				return getAreaFieldBuilder().getBuilder(index);
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.AreaOrBuilder getAreaOrBuilder(
					int index) {
				if (areaBuilder_ == null) {
					return area_.get(index);
				} else {
					return areaBuilder_.getMessageOrBuilder(index);
				}
			}

			public java.util.List<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.AreaOrBuilder> getAreaOrBuilderList() {
				if (areaBuilder_ != null) {
					return areaBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(area_);
				}
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area.Builder addAreaBuilder() {
				return getAreaFieldBuilder()
						.addBuilder(
								br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area
										.getDefaultInstance());
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area.Builder addAreaBuilder(
					int index) {
				return getAreaFieldBuilder()
						.addBuilder(
								index,
								br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area
										.getDefaultInstance());
			}

			public java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area.Builder> getAreaBuilderList() {
				return getAreaFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.AreaOrBuilder> getAreaFieldBuilder() {
				if (areaBuilder_ == null) {
					areaBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.AreaOrBuilder>(
							area_, ((bitField0_ & 0x00000001) == 0x00000001),
							getParentForChildren(), isClean());
					area_ = null;
				}
				return areaBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:MobiPETIC.Areas)
		}

		static {
			defaultInstance = new Areas(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:MobiPETIC.Areas)
	}

	public interface AreaOrBuilder extends com.google.protobuf.MessageOrBuilder {

		// required string id = 1;
		boolean hasId();

		String getId();

		// required string nome = 2;
		boolean hasNome();

		String getNome();
	}

	public static final class Area extends com.google.protobuf.GeneratedMessage
			implements AreaOrBuilder {
		// Use Area.newBuilder() to construct.
		private Area(Builder builder) {
			super(builder);
		}

		private Area(boolean noInit) {
		}

		private static final Area defaultInstance;

		public static Area getDefaultInstance() {
			return defaultInstance;
		}

		public Area getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.internal_static_MobiPETIC_Area_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.internal_static_MobiPETIC_Area_fieldAccessorTable;
		}

		private int bitField0_;
		// required string id = 1;
		public static final int ID_FIELD_NUMBER = 1;
		private java.lang.Object id_;

		public boolean hasId() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public String getId() {
			java.lang.Object ref = id_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					id_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getIdBytes() {
			java.lang.Object ref = id_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				id_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required string nome = 2;
		public static final int NOME_FIELD_NUMBER = 2;
		private java.lang.Object nome_;

		public boolean hasNome() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public String getNome() {
			java.lang.Object ref = nome_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					nome_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getNomeBytes() {
			java.lang.Object ref = nome_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				nome_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			id_ = "";
			nome_ = "";
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasNome()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getIdBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getNomeBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						1, getIdBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						2, getNomeBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.AreaOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.internal_static_MobiPETIC_Area_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.internal_static_MobiPETIC_Area_fieldAccessorTable;
			}

			// Construct using
			// br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				id_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				nome_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area
						.getDescriptor();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area getDefaultInstanceForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area
						.getDefaultInstance();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area build() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area buildPartial() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area result = new br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.id_ = id_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.nome_ = nome_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area) {
					return mergeFrom((br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area other) {
				if (other == br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area
						.getDefaultInstance())
					return this;
				if (other.hasId()) {
					setId(other.getId());
				}
				if (other.hasNome()) {
					setNome(other.getNome());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public final boolean isInitialized() {
				if (!hasId()) {

					return false;
				}
				if (!hasNome()) {

					return false;
				}
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						bitField0_ |= 0x00000001;
						id_ = input.readBytes();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						nome_ = input.readBytes();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required string id = 1;
			private java.lang.Object id_ = "";

			public boolean hasId() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public String getId() {
				java.lang.Object ref = id_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					id_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setId(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				id_ = value;
				onChanged();
				return this;
			}

			public Builder clearId() {
				bitField0_ = (bitField0_ & ~0x00000001);
				id_ = getDefaultInstance().getId();
				onChanged();
				return this;
			}

			void setId(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000001;
				id_ = value;
				onChanged();
			}

			// required string nome = 2;
			private java.lang.Object nome_ = "";

			public boolean hasNome() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public String getNome() {
				java.lang.Object ref = nome_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					nome_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setNome(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				nome_ = value;
				onChanged();
				return this;
			}

			public Builder clearNome() {
				bitField0_ = (bitField0_ & ~0x00000002);
				nome_ = getDefaultInstance().getNome();
				onChanged();
				return this;
			}

			void setNome(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000002;
				nome_ = value;
				onChanged();
			}

			// @@protoc_insertion_point(builder_scope:MobiPETIC.Area)
		}

		static {
			defaultInstance = new Area(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:MobiPETIC.Area)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_MobiPETIC_Areas_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_MobiPETIC_Areas_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_MobiPETIC_Area_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_MobiPETIC_Area_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\017Areasfile.proto\022\tMobiPETIC\"&\n\005Areas\022\035\n"
				+ "\004area\030\001 \003(\0132\017.MobiPETIC.Area\" \n\004Area\022\n\n\002"
				+ "id\030\001 \002(\t\022\014\n\004nome\030\002 \002(\tBC\n4br.ufs.dcomp.g"
				+ "pes.peticwizard.presentation.MobiPETICB\013" + "AreasProtos" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_MobiPETIC_Areas_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_MobiPETIC_Areas_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_MobiPETIC_Areas_descriptor,
						new java.lang.String[] { "Area", },
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas.class,
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Areas.Builder.class);
				internal_static_MobiPETIC_Area_descriptor = getDescriptor()
						.getMessageTypes().get(1);
				internal_static_MobiPETIC_Area_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_MobiPETIC_Area_descriptor,
						new java.lang.String[] { "Id", "Nome", },
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area.class,
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.AreasProtos.Area.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
