// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Questoesfile.proto

package br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC;

public final class QuestoesMaturidadeProtos {
	private QuestoesMaturidadeProtos() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface QuestoesOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// repeated .MobiPETIC.Questao questao = 1;
		java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao> getQuestaoList();

		br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao getQuestao(
				int index);

		int getQuestaoCount();

		java.util.List<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.QuestaoOrBuilder> getQuestaoOrBuilderList();

		br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.QuestaoOrBuilder getQuestaoOrBuilder(
				int index);
	}

	public static final class Questoes extends
			com.google.protobuf.GeneratedMessage implements QuestoesOrBuilder {
		// Use Questoes.newBuilder() to construct.
		private Questoes(Builder builder) {
			super(builder);
		}

		private Questoes(boolean noInit) {
		}

		private static final Questoes defaultInstance;

		public static Questoes getDefaultInstance() {
			return defaultInstance;
		}

		public Questoes getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.internal_static_MobiPETIC_Questoes_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.internal_static_MobiPETIC_Questoes_fieldAccessorTable;
		}

		// repeated .MobiPETIC.Questao questao = 1;
		public static final int QUESTAO_FIELD_NUMBER = 1;
		private java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao> questao_;

		public java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao> getQuestaoList() {
			return questao_;
		}

		public java.util.List<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.QuestaoOrBuilder> getQuestaoOrBuilderList() {
			return questao_;
		}

		public int getQuestaoCount() {
			return questao_.size();
		}

		public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao getQuestao(
				int index) {
			return questao_.get(index);
		}

		public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.QuestaoOrBuilder getQuestaoOrBuilder(
				int index) {
			return questao_.get(index);
		}

		private void initFields() {
			questao_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			for (int i = 0; i < getQuestaoCount(); i++) {
				if (!getQuestao(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < questao_.size(); i++) {
				output.writeMessage(1, questao_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < questao_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(1, questao_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.QuestoesOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.internal_static_MobiPETIC_Questoes_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.internal_static_MobiPETIC_Questoes_fieldAccessorTable;
			}

			// Construct using
			// br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getQuestaoFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				if (questaoBuilder_ == null) {
					questao_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					questaoBuilder_.clear();
				}
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes
						.getDescriptor();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes getDefaultInstanceForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes
						.getDefaultInstance();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes build() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes buildPartial() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes result = new br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes(
						this);
				int from_bitField0_ = bitField0_;
				if (questaoBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						questao_ = java.util.Collections
								.unmodifiableList(questao_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.questao_ = questao_;
				} else {
					result.questao_ = questaoBuilder_.build();
				}
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes) {
					return mergeFrom((br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes other) {
				if (other == br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes
						.getDefaultInstance())
					return this;
				if (questaoBuilder_ == null) {
					if (!other.questao_.isEmpty()) {
						if (questao_.isEmpty()) {
							questao_ = other.questao_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureQuestaoIsMutable();
							questao_.addAll(other.questao_);
						}
						onChanged();
					}
				} else {
					if (!other.questao_.isEmpty()) {
						if (questaoBuilder_.isEmpty()) {
							questaoBuilder_.dispose();
							questaoBuilder_ = null;
							questao_ = other.questao_;
							bitField0_ = (bitField0_ & ~0x00000001);
							questaoBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getQuestaoFieldBuilder()
									: null;
						} else {
							questaoBuilder_.addAllMessages(other.questao_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public final boolean isInitialized() {
				for (int i = 0; i < getQuestaoCount(); i++) {
					if (!getQuestao(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao.Builder subBuilder = br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao
								.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addQuestao(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// repeated .MobiPETIC.Questao questao = 1;
			private java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao> questao_ = java.util.Collections
					.emptyList();

			private void ensureQuestaoIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					questao_ = new java.util.ArrayList<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao>(
							questao_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.QuestaoOrBuilder> questaoBuilder_;

			public java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao> getQuestaoList() {
				if (questaoBuilder_ == null) {
					return java.util.Collections.unmodifiableList(questao_);
				} else {
					return questaoBuilder_.getMessageList();
				}
			}

			public int getQuestaoCount() {
				if (questaoBuilder_ == null) {
					return questao_.size();
				} else {
					return questaoBuilder_.getCount();
				}
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao getQuestao(
					int index) {
				if (questaoBuilder_ == null) {
					return questao_.get(index);
				} else {
					return questaoBuilder_.getMessage(index);
				}
			}

			public Builder setQuestao(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao value) {
				if (questaoBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureQuestaoIsMutable();
					questao_.set(index, value);
					onChanged();
				} else {
					questaoBuilder_.setMessage(index, value);
				}
				return this;
			}

			public Builder setQuestao(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao.Builder builderForValue) {
				if (questaoBuilder_ == null) {
					ensureQuestaoIsMutable();
					questao_.set(index, builderForValue.build());
					onChanged();
				} else {
					questaoBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addQuestao(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao value) {
				if (questaoBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureQuestaoIsMutable();
					questao_.add(value);
					onChanged();
				} else {
					questaoBuilder_.addMessage(value);
				}
				return this;
			}

			public Builder addQuestao(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao value) {
				if (questaoBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureQuestaoIsMutable();
					questao_.add(index, value);
					onChanged();
				} else {
					questaoBuilder_.addMessage(index, value);
				}
				return this;
			}

			public Builder addQuestao(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao.Builder builderForValue) {
				if (questaoBuilder_ == null) {
					ensureQuestaoIsMutable();
					questao_.add(builderForValue.build());
					onChanged();
				} else {
					questaoBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			public Builder addQuestao(
					int index,
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao.Builder builderForValue) {
				if (questaoBuilder_ == null) {
					ensureQuestaoIsMutable();
					questao_.add(index, builderForValue.build());
					onChanged();
				} else {
					questaoBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addAllQuestao(
					java.lang.Iterable<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao> values) {
				if (questaoBuilder_ == null) {
					ensureQuestaoIsMutable();
					super.addAll(values, questao_);
					onChanged();
				} else {
					questaoBuilder_.addAllMessages(values);
				}
				return this;
			}

			public Builder clearQuestao() {
				if (questaoBuilder_ == null) {
					questao_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					questaoBuilder_.clear();
				}
				return this;
			}

			public Builder removeQuestao(int index) {
				if (questaoBuilder_ == null) {
					ensureQuestaoIsMutable();
					questao_.remove(index);
					onChanged();
				} else {
					questaoBuilder_.remove(index);
				}
				return this;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao.Builder getQuestaoBuilder(
					int index) {
				return getQuestaoFieldBuilder().getBuilder(index);
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.QuestaoOrBuilder getQuestaoOrBuilder(
					int index) {
				if (questaoBuilder_ == null) {
					return questao_.get(index);
				} else {
					return questaoBuilder_.getMessageOrBuilder(index);
				}
			}

			public java.util.List<? extends br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.QuestaoOrBuilder> getQuestaoOrBuilderList() {
				if (questaoBuilder_ != null) {
					return questaoBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(questao_);
				}
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao.Builder addQuestaoBuilder() {
				return getQuestaoFieldBuilder()
						.addBuilder(
								br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao
										.getDefaultInstance());
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao.Builder addQuestaoBuilder(
					int index) {
				return getQuestaoFieldBuilder()
						.addBuilder(
								index,
								br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao
										.getDefaultInstance());
			}

			public java.util.List<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao.Builder> getQuestaoBuilderList() {
				return getQuestaoFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.QuestaoOrBuilder> getQuestaoFieldBuilder() {
				if (questaoBuilder_ == null) {
					questaoBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao.Builder, br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.QuestaoOrBuilder>(
							questao_,
							((bitField0_ & 0x00000001) == 0x00000001),
							getParentForChildren(), isClean());
					questao_ = null;
				}
				return questaoBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:MobiPETIC.Questoes)
		}

		static {
			defaultInstance = new Questoes(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:MobiPETIC.Questoes)
	}

	public interface QuestaoOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// required int32 id = 1;
		boolean hasId();

		int getId();

		// required int32 nivel = 2;
		boolean hasNivel();

		int getNivel();

		// required string descricao = 3;
		boolean hasDescricao();

		String getDescricao();
	}

	public static final class Questao extends
			com.google.protobuf.GeneratedMessage implements QuestaoOrBuilder {
		// Use Questao.newBuilder() to construct.
		private Questao(Builder builder) {
			super(builder);
		}

		private Questao(boolean noInit) {
		}

		private static final Questao defaultInstance;

		public static Questao getDefaultInstance() {
			return defaultInstance;
		}

		public Questao getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.internal_static_MobiPETIC_Questao_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.internal_static_MobiPETIC_Questao_fieldAccessorTable;
		}

		private int bitField0_;
		// required int32 id = 1;
		public static final int ID_FIELD_NUMBER = 1;
		private int id_;

		public boolean hasId() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		public int getId() {
			return id_;
		}

		// required int32 nivel = 2;
		public static final int NIVEL_FIELD_NUMBER = 2;
		private int nivel_;

		public boolean hasNivel() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		public int getNivel() {
			return nivel_;
		}

		// required string descricao = 3;
		public static final int DESCRICAO_FIELD_NUMBER = 3;
		private java.lang.Object descricao_;

		public boolean hasDescricao() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		public String getDescricao() {
			java.lang.Object ref = descricao_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					descricao_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getDescricaoBytes() {
			java.lang.Object ref = descricao_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				descricao_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			id_ = 0;
			nivel_ = 0;
			descricao_ = "";
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasNivel()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasDescricao()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(1, id_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeInt32(2, nivel_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeBytes(3, getDescricaoBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						1, id_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						2, nivel_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						3, getDescricaoBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.QuestaoOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.internal_static_MobiPETIC_Questao_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.internal_static_MobiPETIC_Questao_fieldAccessorTable;
			}

			// Construct using
			// br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				id_ = 0;
				bitField0_ = (bitField0_ & ~0x00000001);
				nivel_ = 0;
				bitField0_ = (bitField0_ & ~0x00000002);
				descricao_ = "";
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao
						.getDescriptor();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao getDefaultInstanceForType() {
				return br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao
						.getDefaultInstance();
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao build() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result)
							.asInvalidProtocolBufferException();
				}
				return result;
			}

			public br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao buildPartial() {
				br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao result = new br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.id_ = id_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.nivel_ = nivel_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.descricao_ = descricao_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao) {
					return mergeFrom((br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao other) {
				if (other == br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao
						.getDefaultInstance())
					return this;
				if (other.hasId()) {
					setId(other.getId());
				}
				if (other.hasNivel()) {
					setNivel(other.getNivel());
				}
				if (other.hasDescricao()) {
					setDescricao(other.getDescricao());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public final boolean isInitialized() {
				if (!hasId()) {

					return false;
				}
				if (!hasNivel()) {

					return false;
				}
				if (!hasDescricao()) {

					return false;
				}
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						id_ = input.readInt32();
						break;
					}
					case 16: {
						bitField0_ |= 0x00000002;
						nivel_ = input.readInt32();
						break;
					}
					case 26: {
						bitField0_ |= 0x00000004;
						descricao_ = input.readBytes();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// required int32 id = 1;
			private int id_;

			public boolean hasId() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			public int getId() {
				return id_;
			}

			public Builder setId(int value) {
				bitField0_ |= 0x00000001;
				id_ = value;
				onChanged();
				return this;
			}

			public Builder clearId() {
				bitField0_ = (bitField0_ & ~0x00000001);
				id_ = 0;
				onChanged();
				return this;
			}

			// required int32 nivel = 2;
			private int nivel_;

			public boolean hasNivel() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			public int getNivel() {
				return nivel_;
			}

			public Builder setNivel(int value) {
				bitField0_ |= 0x00000002;
				nivel_ = value;
				onChanged();
				return this;
			}

			public Builder clearNivel() {
				bitField0_ = (bitField0_ & ~0x00000002);
				nivel_ = 0;
				onChanged();
				return this;
			}

			// required string descricao = 3;
			private java.lang.Object descricao_ = "";

			public boolean hasDescricao() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			public String getDescricao() {
				java.lang.Object ref = descricao_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					descricao_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setDescricao(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				descricao_ = value;
				onChanged();
				return this;
			}

			public Builder clearDescricao() {
				bitField0_ = (bitField0_ & ~0x00000004);
				descricao_ = getDefaultInstance().getDescricao();
				onChanged();
				return this;
			}

			void setDescricao(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000004;
				descricao_ = value;
				onChanged();
			}

			// @@protoc_insertion_point(builder_scope:MobiPETIC.Questao)
		}

		static {
			defaultInstance = new Questao(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:MobiPETIC.Questao)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_MobiPETIC_Questoes_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_MobiPETIC_Questoes_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_MobiPETIC_Questao_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_MobiPETIC_Questao_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\022Questoesfile.proto\022\tMobiPETIC\"/\n\010Quest"
				+ "oes\022#\n\007questao\030\001 \003(\0132\022.MobiPETIC.Questao"
				+ "\"7\n\007Questao\022\n\n\002id\030\001 \002(\005\022\r\n\005nivel\030\002 \002(\005\022\021"
				+ "\n\tdescricao\030\003 \002(\tBP\n4br.ufs.dcomp.gpes.p"
				+ "eticwizard.presentation.MobiPETICB\030Quest"
				+ "oesMaturidadeProtos" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_MobiPETIC_Questoes_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_MobiPETIC_Questoes_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_MobiPETIC_Questoes_descriptor,
						new java.lang.String[] { "Questao", },
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes.class,
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questoes.Builder.class);
				internal_static_MobiPETIC_Questao_descriptor = getDescriptor()
						.getMessageTypes().get(1);
				internal_static_MobiPETIC_Questao_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_MobiPETIC_Questao_descriptor,
						new java.lang.String[] { "Id", "Nivel", "Descricao", },
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao.class,
						br.ufs.dcomp.gpes.peticwizard.presentation.MobiPETIC.QuestoesMaturidadeProtos.Questao.Builder.class);
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
